// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package forowner
type GetQOwner_typeQueryParameterType int

const (
    ORGANIZATIONS_GETQOWNER_TYPEQUERYPARAMETERTYPE GetQOwner_typeQueryParameterType = iota
)

func (i GetQOwner_typeQueryParameterType) String() string {
    return []string{"organizations"}[i]
}
func ParseGetQOwner_typeQueryParameterType(v string) (any, error) {
    result := ORGANIZATIONS_GETQOWNER_TYPEQUERYPARAMETERTYPE
    switch v {
        case "organizations":
            result = ORGANIZATIONS_GETQOWNER_TYPEQUERYPARAMETERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGetQOwner_typeQueryParameterType(values []GetQOwner_typeQueryParameterType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GetQOwner_typeQueryParameterType) isMultiValue() bool {
    return false
}
