// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package projects
type ProjectsPostRequestBody_data_type int

const (
    PROJECTS_PROJECTSPOSTREQUESTBODY_DATA_TYPE ProjectsPostRequestBody_data_type = iota
)

func (i ProjectsPostRequestBody_data_type) String() string {
    return []string{"projects"}[i]
}
func ParseProjectsPostRequestBody_data_type(v string) (any, error) {
    result := PROJECTS_PROJECTSPOSTREQUESTBODY_DATA_TYPE
    switch v {
        case "projects":
            result = PROJECTS_PROJECTSPOSTREQUESTBODY_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeProjectsPostRequestBody_data_type(values []ProjectsPostRequestBody_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i ProjectsPostRequestBody_data_type) isMultiValue() bool {
    return false
}
