// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package devportal

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// OrganizationsItemProjectsRequestBuilder builds and executes requests for operations under \dev-portal\organizations\{organization_name}\projects
type OrganizationsItemProjectsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByProject_external_id gets an item from the github.com/hashicorp/go-tfe/v2/api.devPortal.organizations.item.projects.item collection
// returns a *OrganizationsItemProjectsWithProject_external_ItemRequestBuilder when successful
func (m *OrganizationsItemProjectsRequestBuilder) ByProject_external_id(project_external_id string)(*OrganizationsItemProjectsWithProject_external_ItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if project_external_id != "" {
        urlTplParams["project_external_id"] = project_external_id
    }
    return NewOrganizationsItemProjectsWithProject_external_ItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewOrganizationsItemProjectsRequestBuilderInternal instantiates a new OrganizationsItemProjectsRequestBuilder and sets the default values.
func NewOrganizationsItemProjectsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OrganizationsItemProjectsRequestBuilder) {
    m := &OrganizationsItemProjectsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/dev-portal/organizations/{organization_name}/projects", pathParameters),
    }
    return m
}
// NewOrganizationsItemProjectsRequestBuilder instantiates a new OrganizationsItemProjectsRequestBuilder and sets the default values.
func NewOrganizationsItemProjectsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OrganizationsItemProjectsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewOrganizationsItemProjectsRequestBuilderInternal(urlParams, requestAdapter)
}
