// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package devportal

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16 "github.com/hashicorp/go-tfe/v2/api/models"
)

// OrganizationsItemTemplatesRequestBuilder builds and executes requests for operations under \dev-portal\organizations\{organization_name}\templates
type OrganizationsItemTemplatesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// OrganizationsItemTemplatesRequestBuilderGetQueryParameters returns all application templates available in an organization.This operation is considered BETA, is SUBJECT TO CHANGE, and may be unavailable to some users.
type OrganizationsItemTemplatesRequestBuilderGetQueryParameters struct {
    // Return only the specified fields for tdp-templates resource(s) in the response. Use underscores for identifiers that contain a dash: For example, auto_apply instead of auto-apply. An empty value indicates that no fields should be returned.
    FieldstdpTemplates []string "uriparametername:\"fields%5Btdp%2Dtemplates%5D\""
    // The page number to retrieve.
    Pagenumber *int32 "uriparametername:\"page%5Bnumber%5D\""
    // The number of items to retrieve per page. Defaults to 20.
    Pagesize *int32 "uriparametername:\"page%5Bsize%5D\""
}
// ByTemplate_id gets an item from the github.com/hashicorp/go-tfe/v2/api.devPortal.organizations.item.templates.item collection
// returns a *OrganizationsItemTemplatesWithTemplate_ItemRequestBuilder when successful
func (m *OrganizationsItemTemplatesRequestBuilder) ByTemplate_id(template_id string)(*OrganizationsItemTemplatesWithTemplate_ItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if template_id != "" {
        urlTplParams["template_id"] = template_id
    }
    return NewOrganizationsItemTemplatesWithTemplate_ItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewOrganizationsItemTemplatesRequestBuilderInternal instantiates a new OrganizationsItemTemplatesRequestBuilder and sets the default values.
func NewOrganizationsItemTemplatesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OrganizationsItemTemplatesRequestBuilder) {
    m := &OrganizationsItemTemplatesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/dev-portal/organizations/{organization_name}/templates{?fields%5Btdp%2Dtemplates%5D,page%5Bnumber%5D*,page%5Bsize%5D*}", pathParameters),
    }
    return m
}
// NewOrganizationsItemTemplatesRequestBuilder instantiates a new OrganizationsItemTemplatesRequestBuilder and sets the default values.
func NewOrganizationsItemTemplatesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*OrganizationsItemTemplatesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewOrganizationsItemTemplatesRequestBuilderInternal(urlParams, requestAdapter)
}
// Get returns all application templates available in an organization.This operation is considered BETA, is SUBJECT TO CHANGE, and may be unavailable to some users.
// returns a TdpTemplateCollectionEnvelopeable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *OrganizationsItemTemplatesRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[OrganizationsItemTemplatesRequestBuilderGetQueryParameters])(i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.TdpTemplateCollectionEnvelopeable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.CreateTdpTemplateCollectionEnvelopeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.TdpTemplateCollectionEnvelopeable), nil
}
// Post creates a new application template in an organization.This operation is considered BETA, is SUBJECT TO CHANGE, and may be unavailable to some users.
// returns a TdpTemplateEnvelopeable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *OrganizationsItemTemplatesRequestBuilder) Post(ctx context.Context, body i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.TdpTemplateEnvelopeable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.TdpTemplateEnvelopeable, error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, body, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.CreateTdpTemplateEnvelopeFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.TdpTemplateEnvelopeable), nil
}
// ToGetRequestInformation returns all application templates available in an organization.This operation is considered BETA, is SUBJECT TO CHANGE, and may be unavailable to some users.
// returns a *RequestInformation when successful
func (m *OrganizationsItemTemplatesRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[OrganizationsItemTemplatesRequestBuilderGetQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    return requestInfo, nil
}
// ToPostRequestInformation creates a new application template in an organization.This operation is considered BETA, is SUBJECT TO CHANGE, and may be unavailable to some users.
// returns a *RequestInformation when successful
func (m *OrganizationsItemTemplatesRequestBuilder) ToPostRequestInformation(ctx context.Context, body i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.TdpTemplateEnvelopeable, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    err := requestInfo.SetContentFromParsable(ctx, m.BaseRequestBuilder.RequestAdapter, "application/vnd.api+json", body)
    if err != nil {
        return nil, err
    }
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *OrganizationsItemTemplatesRequestBuilder when successful
func (m *OrganizationsItemTemplatesRequestBuilder) WithUrl(rawUrl string)(*OrganizationsItemTemplatesRequestBuilder) {
    return NewOrganizationsItemTemplatesRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
