// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package policysets

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The branch property
    branch *string
    // The identifier property
    identifier *string
    // The ingressSubmodules property
    ingressSubmodules *bool
    // The oauthTokenId property
    oauthTokenId *string
}
// NewItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo instantiates a new ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo and sets the default values.
func NewItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo()(*ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) {
    m := &ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetBranch gets the branch property value. The branch property
// returns a *string when successful
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) GetBranch()(*string) {
    return m.branch
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["branch"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetBranch(val)
        }
        return nil
    }
    res["identifier"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentifier(val)
        }
        return nil
    }
    res["ingress-submodules"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIngressSubmodules(val)
        }
        return nil
    }
    res["oauth-token-id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOauthTokenId(val)
        }
        return nil
    }
    return res
}
// GetIdentifier gets the identifier property value. The identifier property
// returns a *string when successful
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) GetIdentifier()(*string) {
    return m.identifier
}
// GetIngressSubmodules gets the ingress-submodules property value. The ingressSubmodules property
// returns a *bool when successful
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) GetIngressSubmodules()(*bool) {
    return m.ingressSubmodules
}
// GetOauthTokenId gets the oauth-token-id property value. The oauthTokenId property
// returns a *string when successful
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) GetOauthTokenId()(*string) {
    return m.oauthTokenId
}
// Serialize serializes information the current object
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("branch", m.GetBranch())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("identifier", m.GetIdentifier())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("ingress-submodules", m.GetIngressSubmodules())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("oauth-token-id", m.GetOauthTokenId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetBranch sets the branch property value. The branch property
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) SetBranch(value *string)() {
    m.branch = value
}
// SetIdentifier sets the identifier property value. The identifier property
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) SetIdentifier(value *string)() {
    m.identifier = value
}
// SetIngressSubmodules sets the ingress-submodules property value. The ingressSubmodules property
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) SetIngressSubmodules(value *bool)() {
    m.ingressSubmodules = value
}
// SetOauthTokenId sets the oauth-token-id property value. The oauthTokenId property
func (m *ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepo) SetOauthTokenId(value *string)() {
    m.oauthTokenId = value
}
type ItemWithPolicy_set_PatchRequestBody_data_attributes_vcsRepoable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetBranch()(*string)
    GetIdentifier()(*string)
    GetIngressSubmodules()(*bool)
    GetOauthTokenId()(*string)
    SetBranch(value *string)()
    SetIdentifier(value *string)()
    SetIngressSubmodules(value *bool)()
    SetOauthTokenId(value *string)()
}
