// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package taskconfigs
type GetFilterTaskCategoryQueryParameterType int

const (
    TASK_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE GetFilterTaskCategoryQueryParameterType = iota
    HOOK_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE
    NATIVE_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE
)

func (i GetFilterTaskCategoryQueryParameterType) String() string {
    return []string{"task", "hook", "native"}[i]
}
func ParseGetFilterTaskCategoryQueryParameterType(v string) (any, error) {
    result := TASK_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE
    switch v {
        case "task":
            result = TASK_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE
        case "hook":
            result = HOOK_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE
        case "native":
            result = NATIVE_GETFILTERTASKCATEGORYQUERYPARAMETERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGetFilterTaskCategoryQueryParameterType(values []GetFilterTaskCategoryQueryParameterType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GetFilterTaskCategoryQueryParameterType) isMultiValue() bool {
    return false
}
