run:
  timeout: 5m
linters:
#enabled by default: deadcode, errcheck, gosimple, govet, ineffasign, staticcheck, struccheck, typecheck, unused, varcheck
  enable:
    - whitespace #https://github.com/ultraware/whitespace
    # - noctx #https://github.com/sonatard/noctx
    - nilerr #https://github.com/gostaticanalysis/nilerr
    - nestif #https://github.com/nakabonne/nestif
    # - gocritic #https://github.com/go-critic/go-critic #TODO: reasses usefulness
    # - goconst #https://github.com/jgautheron/goconst #TODO: reasses usefulness
    - exportloopref #https://github.com/kyoh86/exportloopref
    # - errname #https://github.com/Antonboom/errname #TODO: reasses usefulness
    # - errorlint #https://github.com/polyfloyd/go-errorlint #TODO: reasses usefulness
    - bodyclose #https://github.com/timakin/bodyclose
    # - cyclop #https://github.com/bkielbasa/cyclop
    - errcheck #https://github.com/kisielk/errcheck
    - stylecheck #https://github.com/dominikh/go-tools/tree/master/stylecheck
    - revive #golint is deprecated and golangci-lint recommends to use revive instead https://github.com/mgechev/revive
    #other deprecated lint libraries: maligned, scopelint, interfacer
issues:
  exclude-rules:
  - path: _test\.go
    linters:
    - unused
    - deadcode
linters-settings:
  errcheck:
    # https://github.com/kisielk/errcheck#excluding-functions
    check-type-assertions: true
    check-blank: true
   
  revive:
    # see https://github.com/mgechev/revive#available-rules for details.
    ignore-generated-header: false #recommended in their configuration
    severity: warning
    rules:
      - name: indent-error-flow #Prevents redundant else statements
        severity: warning
      - name: useless-break
        severity: warning