version: "2"
linters:
  enable:
    - bodyclose
    - goconst
    - gocritic
    - misspell
    - nestif
    - nilerr
    - revive
    - staticcheck
    - unparam
    - whitespace
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 20
      min-occurrences: 5
      ignore-calls: false
    gocritic:
      disabled-checks:
        - unnamedResult
        - hugeParam
        - singleCaseSwitch
        - ifElseChain
      enabled-tags:
        - diagnostic
        - opinionated
        - performance
    revive:
      severity: warning
      rules:
        - name: indent-error-flow
          severity: warning
        - name: useless-break
          severity: warning
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - staticcheck
        text: Ascii
      - linters:
          - deadcode
          - unparam
          - unused
          - errcheck
        path: _test\.go
      - linters:
          - goconst
        path: (.+)_test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
