// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package providersets
type GetIncludeQueryParameterType int

const (
    PROJECTS_GETINCLUDEQUERYPARAMETERTYPE GetIncludeQueryParameterType = iota
    WORKSPACES_GETINCLUDEQUERYPARAMETERTYPE
)

func (i GetIncludeQueryParameterType) String() string {
    return []string{"projects", "workspaces"}[i]
}
func ParseGetIncludeQueryParameterType(v string) (any, error) {
    result := PROJECTS_GETINCLUDEQUERYPARAMETERTYPE
    switch v {
        case "projects":
            result = PROJECTS_GETINCLUDEQUERYPARAMETERTYPE
        case "workspaces":
            result = WORKSPACES_GETINCLUDEQUERYPARAMETERTYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGetIncludeQueryParameterType(values []GetIncludeQueryParameterType) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GetIncludeQueryParameterType) isMultiValue() bool {
    return false
}
