// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package stackdiagnostics

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// StackDiagnosticsRequestBuilder builds and executes requests for operations under \stack-diagnostics
type StackDiagnosticsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByStack_diagnostic_id gets an item from the github.com/hashicorp/go-tfe/v2/api.stackDiagnostics.item collection
// returns a *WithStack_diagnostic_ItemRequestBuilder when successful
func (m *StackDiagnosticsRequestBuilder) ByStack_diagnostic_id(stack_diagnostic_id string)(*WithStack_diagnostic_ItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if stack_diagnostic_id != "" {
        urlTplParams["stack_diagnostic_id"] = stack_diagnostic_id
    }
    return NewWithStack_diagnostic_ItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewStackDiagnosticsRequestBuilderInternal instantiates a new StackDiagnosticsRequestBuilder and sets the default values.
func NewStackDiagnosticsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StackDiagnosticsRequestBuilder) {
    m := &StackDiagnosticsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/stack-diagnostics", pathParameters),
    }
    return m
}
// NewStackDiagnosticsRequestBuilder instantiates a new StackDiagnosticsRequestBuilder and sets the default values.
func NewStackDiagnosticsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StackDiagnosticsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewStackDiagnosticsRequestBuilderInternal(urlParams, requestAdapter)
}
