// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package stackdeploymentgroups

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// StackDeploymentGroupsRequestBuilder builds and executes requests for operations under \stack-deployment-groups
type StackDeploymentGroupsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ByStack_deployment_group_id gets an item from the github.com/hashicorp/go-tfe/api.stackDeploymentGroups.item collection
// returns a *WithStack_deployment_group_ItemRequestBuilder when successful
func (m *StackDeploymentGroupsRequestBuilder) ByStack_deployment_group_id(stack_deployment_group_id string)(*WithStack_deployment_group_ItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if stack_deployment_group_id != "" {
        urlTplParams["stack_deployment_group_id"] = stack_deployment_group_id
    }
    return NewWithStack_deployment_group_ItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewStackDeploymentGroupsRequestBuilderInternal instantiates a new StackDeploymentGroupsRequestBuilder and sets the default values.
func NewStackDeploymentGroupsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StackDeploymentGroupsRequestBuilder) {
    m := &StackDeploymentGroupsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/stack-deployment-groups", pathParameters),
    }
    return m
}
// NewStackDeploymentGroupsRequestBuilder instantiates a new StackDeploymentGroupsRequestBuilder and sets the default values.
func NewStackDeploymentGroupsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*StackDeploymentGroupsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewStackDeploymentGroupsRequestBuilderInternal(urlParams, requestAdapter)
}
