// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package applies

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16 "github.com/hashicorp/go-tfe/v2/api/models"
)

// ItemActionsPermanentlyDeleteBackingDataRequestBuilder builds and executes requests for operations under \applies\{id}\actions\permanently-delete-backing-data
type ItemActionsPermanentlyDeleteBackingDataRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewItemActionsPermanentlyDeleteBackingDataRequestBuilderInternal instantiates a new ItemActionsPermanentlyDeleteBackingDataRequestBuilder and sets the default values.
func NewItemActionsPermanentlyDeleteBackingDataRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemActionsPermanentlyDeleteBackingDataRequestBuilder) {
    m := &ItemActionsPermanentlyDeleteBackingDataRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/applies/{id}/actions/permanently-delete-backing-data", pathParameters),
    }
    return m
}
// NewItemActionsPermanentlyDeleteBackingDataRequestBuilder instantiates a new ItemActionsPermanentlyDeleteBackingDataRequestBuilder and sets the default values.
func NewItemActionsPermanentlyDeleteBackingDataRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemActionsPermanentlyDeleteBackingDataRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemActionsPermanentlyDeleteBackingDataRequestBuilderInternal(urlParams, requestAdapter)
}
// Post permanently delete the backing files associated with an apply that has been soft deleted. This action cannot be undone.This operation is only available in Terraform Enterprise.
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *ItemActionsPermanentlyDeleteBackingDataRequestBuilder) Post(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(error) {
    requestInfo, err := m.ToPostRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": i05d5aa6b14db285c2e8df48c915f7a7082b77b17cca0def522e18528f80bec16.CreateErrorsFromDiscriminatorValue,
    }
    err = m.BaseRequestBuilder.RequestAdapter.SendNoContent(ctx, requestInfo, errorMapping)
    if err != nil {
        return err
    }
    return nil
}
// ToPostRequestInformation permanently delete the backing files associated with an apply that has been soft deleted. This action cannot be undone.This operation is only available in Terraform Enterprise.
// returns a *RequestInformation when successful
func (m *ItemActionsPermanentlyDeleteBackingDataRequestBuilder) ToPostRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.DefaultQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.POST, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemActionsPermanentlyDeleteBackingDataRequestBuilder when successful
func (m *ItemActionsPermanentlyDeleteBackingDataRequestBuilder) WithUrl(rawUrl string)(*ItemActionsPermanentlyDeleteBackingDataRequestBuilder) {
    return NewItemActionsPermanentlyDeleteBackingDataRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
