// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package organizations

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ItemOrganizationMembershipsPostRequestBody_data struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The attributes property
    attributes ItemOrganizationMembershipsPostRequestBody_data_attributesable
    // The relationships property
    relationships ItemOrganizationMembershipsPostRequestBody_data_relationshipsable
}
// NewItemOrganizationMembershipsPostRequestBody_data instantiates a new ItemOrganizationMembershipsPostRequestBody_data and sets the default values.
func NewItemOrganizationMembershipsPostRequestBody_data()(*ItemOrganizationMembershipsPostRequestBody_data) {
    m := &ItemOrganizationMembershipsPostRequestBody_data{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateItemOrganizationMembershipsPostRequestBody_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemOrganizationMembershipsPostRequestBody_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemOrganizationMembershipsPostRequestBody_data(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ItemOrganizationMembershipsPostRequestBody_data) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAttributes gets the attributes property value. The attributes property
// returns a ItemOrganizationMembershipsPostRequestBody_data_attributesable when successful
func (m *ItemOrganizationMembershipsPostRequestBody_data) GetAttributes()(ItemOrganizationMembershipsPostRequestBody_data_attributesable) {
    return m.attributes
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ItemOrganizationMembershipsPostRequestBody_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["attributes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateItemOrganizationMembershipsPostRequestBody_data_attributesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttributes(val.(ItemOrganizationMembershipsPostRequestBody_data_attributesable))
        }
        return nil
    }
    res["relationships"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateItemOrganizationMembershipsPostRequestBody_data_relationshipsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRelationships(val.(ItemOrganizationMembershipsPostRequestBody_data_relationshipsable))
        }
        return nil
    }
    return res
}
// GetRelationships gets the relationships property value. The relationships property
// returns a ItemOrganizationMembershipsPostRequestBody_data_relationshipsable when successful
func (m *ItemOrganizationMembershipsPostRequestBody_data) GetRelationships()(ItemOrganizationMembershipsPostRequestBody_data_relationshipsable) {
    return m.relationships
}
// Serialize serializes information the current object
func (m *ItemOrganizationMembershipsPostRequestBody_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("attributes", m.GetAttributes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("relationships", m.GetRelationships())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ItemOrganizationMembershipsPostRequestBody_data) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAttributes sets the attributes property value. The attributes property
func (m *ItemOrganizationMembershipsPostRequestBody_data) SetAttributes(value ItemOrganizationMembershipsPostRequestBody_data_attributesable)() {
    m.attributes = value
}
// SetRelationships sets the relationships property value. The relationships property
func (m *ItemOrganizationMembershipsPostRequestBody_data) SetRelationships(value ItemOrganizationMembershipsPostRequestBody_data_relationshipsable)() {
    m.relationships = value
}
type ItemOrganizationMembershipsPostRequestBody_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttributes()(ItemOrganizationMembershipsPostRequestBody_data_attributesable)
    GetRelationships()(ItemOrganizationMembershipsPostRequestBody_data_relationshipsable)
    SetAttributes(value ItemOrganizationMembershipsPostRequestBody_data_attributesable)()
    SetRelationships(value ItemOrganizationMembershipsPostRequestBody_data_relationshipsable)()
}
