// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package organizations

import (
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
)

// ItemRegistryModulesRequestBuilder builds and executes requests for operations under \organizations\{organization_name}\registry-modules
type ItemRegistryModulesRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// NewItemRegistryModulesRequestBuilderInternal instantiates a new ItemRegistryModulesRequestBuilder and sets the default values.
func NewItemRegistryModulesRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemRegistryModulesRequestBuilder) {
    m := &ItemRegistryModulesRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/organizations/{organization_name}/registry-modules", pathParameters),
    }
    return m
}
// NewItemRegistryModulesRequestBuilder instantiates a new ItemRegistryModulesRequestBuilder and sets the default values.
func NewItemRegistryModulesRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemRegistryModulesRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemRegistryModulesRequestBuilderInternal(urlParams, requestAdapter)
}
// Validation the validation property
// returns a *ItemRegistryModulesValidationRequestBuilder when successful
func (m *ItemRegistryModulesRequestBuilder) Validation()(*ItemRegistryModulesValidationRequestBuilder) {
    return NewItemRegistryModulesValidationRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
