# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Lint
description: Lints go-tfe
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: go.mod
        cache: true

    - run: make fmtcheck
      shell: bash

    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/cc3567e3127d8530afb69be1b7bd20ba9ebcc7c1/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCILINT_VERSION
      shell: bash
      env:
        GOLANGCILINT_VERSION: v2.1.5

    - run: make lint
      shell: bash

    - name: verify go.mod and go.sum are consistent
      shell: bash
      run: |
        go mod download
        go mod tidy

    - name: Ensure there are no differences after previous steps
      shell: bash
      run: git diff --exit-code
