# Copyright IBM Corp. 2018, 2026
# SPDX-License-Identifier: MPL-2.0

name: Lint
description: Lints go-tfe
runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod
        cache: true

    - run: make fmtcheck
      shell: bash

    - name: install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/6008b81b81c690c046ffc3fd5bce896da715d5fd/install.sh | sh -s -- -b $(go env GOPATH)/bin $GOLANGCILINT_VERSION
      shell: bash
      env:
        GOLANGCILINT_VERSION: v2.11.3

    - run: make lint
      shell: bash

    - name: get dependencies
      shell: bash
      run: go mod download

    - name: verify go.mod and go.sum are consistent
      shell: bash
      run : go mod tidy

    - name: verify no changes
      shell: bash
      run: git diff --exit-code
