// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package stateversions

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f "github.com/hashicorp/go-tfe/api/models"
)

// WithState_version_ItemRequestBuilder builds and executes requests for operations under \state-versions\{state_version_id}
type WithState_version_ItemRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// WithState_version_ItemRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type WithState_version_ItemRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
}
// NewWithState_version_ItemRequestBuilderInternal instantiates a new WithState_version_ItemRequestBuilder and sets the default values.
func NewWithState_version_ItemRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WithState_version_ItemRequestBuilder) {
    m := &WithState_version_ItemRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/state-versions/{state_version_id}", pathParameters),
    }
    return m
}
// NewWithState_version_ItemRequestBuilder instantiates a new WithState_version_ItemRequestBuilder and sets the default values.
func NewWithState_version_ItemRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*WithState_version_ItemRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewWithState_version_ItemRequestBuilderInternal(urlParams, requestAdapter)
}
// Get show details for a specific state version.
// Deprecated: This method is obsolete. Use GetAsWithState_version_GetResponse instead.
// returns a ItemWithState_version_Responseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *WithState_version_ItemRequestBuilder) Get(ctx context.Context, requestConfiguration *WithState_version_ItemRequestBuilderGetRequestConfiguration)(ItemWithState_version_Responseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemWithState_version_ResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemWithState_version_Responseable), nil
}
// GetAsWithState_version_GetResponse show details for a specific state version.
// returns a ItemWithState_version_GetResponseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *WithState_version_ItemRequestBuilder) GetAsWithState_version_GetResponse(ctx context.Context, requestConfiguration *WithState_version_ItemRequestBuilderGetRequestConfiguration)(ItemWithState_version_GetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemWithState_version_GetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemWithState_version_GetResponseable), nil
}
// Outputs the outputs property
// returns a *ItemOutputsRequestBuilder when successful
func (m *WithState_version_ItemRequestBuilder) Outputs()(*ItemOutputsRequestBuilder) {
    return NewItemOutputsRequestBuilderInternal(m.BaseRequestBuilder.PathParameters, m.BaseRequestBuilder.RequestAdapter)
}
// ToGetRequestInformation show details for a specific state version.
// returns a *RequestInformation when successful
func (m *WithState_version_ItemRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *WithState_version_ItemRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *WithState_version_ItemRequestBuilder when successful
func (m *WithState_version_ItemRequestBuilder) WithUrl(rawUrl string)(*WithState_version_ItemRequestBuilder) {
    return NewWithState_version_ItemRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
