// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package varsets
type VarsetsPostRequestBody_data_relationships_stacks_data_type int

const (
    STACKS_VARSETSPOSTREQUESTBODY_DATA_RELATIONSHIPS_STACKS_DATA_TYPE VarsetsPostRequestBody_data_relationships_stacks_data_type = iota
)

func (i VarsetsPostRequestBody_data_relationships_stacks_data_type) String() string {
    return []string{"stacks"}[i]
}
func ParseVarsetsPostRequestBody_data_relationships_stacks_data_type(v string) (any, error) {
    result := STACKS_VARSETSPOSTREQUESTBODY_DATA_RELATIONSHIPS_STACKS_DATA_TYPE
    switch v {
        case "stacks":
            result = STACKS_VARSETSPOSTREQUESTBODY_DATA_RELATIONSHIPS_STACKS_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeVarsetsPostRequestBody_data_relationships_stacks_data_type(values []VarsetsPostRequestBody_data_relationships_stacks_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i VarsetsPostRequestBody_data_relationships_stacks_data_type) isMultiValue() bool {
    return false
}
