// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package registrycomponents

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f "github.com/hashicorp/go-tfe/api/models"
)

// ItemVersionsItemSubcomponentsRequestBuilder builds and executes requests for operations under \registry-components\{registry_component_id}\versions\{version}\subcomponents
type ItemVersionsItemSubcomponentsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemVersionsItemSubcomponentsRequestBuilderGetQueryParameters list all subcomponents for a specific component version
type ItemVersionsItemSubcomponentsRequestBuilderGetQueryParameters struct {
    // If omitted, the endpoint will return the first page.
    Pagenumber *int32 `uriparametername:"page%5Bnumber%5D"`
    // If omitted, the endpoint will return 20 per page.
    Pagesize *int32 `uriparametername:"page%5Bsize%5D"`
}
// ItemVersionsItemSubcomponentsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemVersionsItemSubcomponentsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *ItemVersionsItemSubcomponentsRequestBuilderGetQueryParameters
}
// NewItemVersionsItemSubcomponentsRequestBuilderInternal instantiates a new ItemVersionsItemSubcomponentsRequestBuilder and sets the default values.
func NewItemVersionsItemSubcomponentsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemVersionsItemSubcomponentsRequestBuilder) {
    m := &ItemVersionsItemSubcomponentsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/registry-components/{registry_component_id}/versions/{version}/subcomponents{?page%5Bnumber%5D*,page%5Bsize%5D*}", pathParameters),
    }
    return m
}
// NewItemVersionsItemSubcomponentsRequestBuilder instantiates a new ItemVersionsItemSubcomponentsRequestBuilder and sets the default values.
func NewItemVersionsItemSubcomponentsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemVersionsItemSubcomponentsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemVersionsItemSubcomponentsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get list all subcomponents for a specific component version
// Deprecated: This method is obsolete. Use GetAsSubcomponentsGetResponse instead.
// returns a ItemVersionsItemSubcomponentsResponseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *ItemVersionsItemSubcomponentsRequestBuilder) Get(ctx context.Context, requestConfiguration *ItemVersionsItemSubcomponentsRequestBuilderGetRequestConfiguration)(ItemVersionsItemSubcomponentsResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemVersionsItemSubcomponentsResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemVersionsItemSubcomponentsResponseable), nil
}
// GetAsSubcomponentsGetResponse list all subcomponents for a specific component version
// returns a ItemVersionsItemSubcomponentsGetResponseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *ItemVersionsItemSubcomponentsRequestBuilder) GetAsSubcomponentsGetResponse(ctx context.Context, requestConfiguration *ItemVersionsItemSubcomponentsRequestBuilderGetRequestConfiguration)(ItemVersionsItemSubcomponentsGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemVersionsItemSubcomponentsGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemVersionsItemSubcomponentsGetResponseable), nil
}
// ToGetRequestInformation list all subcomponents for a specific component version
// returns a *RequestInformation when successful
func (m *ItemVersionsItemSubcomponentsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *ItemVersionsItemSubcomponentsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemVersionsItemSubcomponentsRequestBuilder when successful
func (m *ItemVersionsItemSubcomponentsRequestBuilder) WithUrl(rawUrl string)(*ItemVersionsItemSubcomponentsRequestBuilder) {
    return NewItemVersionsItemSubcomponentsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
