// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminTfpolicyVersions struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The attributes property
    attributes AdminTfpolicyVersions_attributesable
    // The external ID of the TFPolicy version (e.g. tool-xxxxxxxxxxxxxxxx).
    id *string
    // The type property
    typeEscaped *AdminTfpolicyVersions_type
}
// NewAdminTfpolicyVersions instantiates a new AdminTfpolicyVersions and sets the default values.
func NewAdminTfpolicyVersions()(*AdminTfpolicyVersions) {
    m := &AdminTfpolicyVersions{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAdminTfpolicyVersionsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminTfpolicyVersionsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminTfpolicyVersions(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AdminTfpolicyVersions) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAttributes gets the attributes property value. The attributes property
// returns a AdminTfpolicyVersions_attributesable when successful
func (m *AdminTfpolicyVersions) GetAttributes()(AdminTfpolicyVersions_attributesable) {
    return m.attributes
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminTfpolicyVersions) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["attributes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAdminTfpolicyVersions_attributesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttributes(val.(AdminTfpolicyVersions_attributesable))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAdminTfpolicyVersions_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*AdminTfpolicyVersions_type))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The external ID of the TFPolicy version (e.g. tool-xxxxxxxxxxxxxxxx).
// returns a *string when successful
func (m *AdminTfpolicyVersions) GetId()(*string) {
    return m.id
}
// GetTypeEscaped gets the type property value. The type property
// returns a *AdminTfpolicyVersions_type when successful
func (m *AdminTfpolicyVersions) GetTypeEscaped()(*AdminTfpolicyVersions_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *AdminTfpolicyVersions) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("attributes", m.GetAttributes())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AdminTfpolicyVersions) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAttributes sets the attributes property value. The attributes property
func (m *AdminTfpolicyVersions) SetAttributes(value AdminTfpolicyVersions_attributesable)() {
    m.attributes = value
}
// SetId sets the id property value. The external ID of the TFPolicy version (e.g. tool-xxxxxxxxxxxxxxxx).
func (m *AdminTfpolicyVersions) SetId(value *string)() {
    m.id = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *AdminTfpolicyVersions) SetTypeEscaped(value *AdminTfpolicyVersions_type)() {
    m.typeEscaped = value
}
type AdminTfpolicyVersionsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttributes()(AdminTfpolicyVersions_attributesable)
    GetId()(*string)
    GetTypeEscaped()(*AdminTfpolicyVersions_type)
    SetAttributes(value AdminTfpolicyVersions_attributesable)()
    SetId(value *string)()
    SetTypeEscaped(value *AdminTfpolicyVersions_type)()
}
