// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
// Visual style controlling how the banner is rendered.
type AdminBanners_attributes_style int

const (
    INFO_ADMINBANNERS_ATTRIBUTES_STYLE AdminBanners_attributes_style = iota
    WARNING_ADMINBANNERS_ATTRIBUTES_STYLE
    CRITICAL_ADMINBANNERS_ATTRIBUTES_STYLE
)

func (i AdminBanners_attributes_style) String() string {
    return []string{"info", "warning", "critical"}[i]
}
func ParseAdminBanners_attributes_style(v string) (any, error) {
    result := INFO_ADMINBANNERS_ATTRIBUTES_STYLE
    switch v {
        case "info":
            result = INFO_ADMINBANNERS_ATTRIBUTES_STYLE
        case "warning":
            result = WARNING_ADMINBANNERS_ATTRIBUTES_STYLE
        case "critical":
            result = CRITICAL_ADMINBANNERS_ATTRIBUTES_STYLE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAdminBanners_attributes_style(values []AdminBanners_attributes_style) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AdminBanners_attributes_style) isMultiValue() bool {
    return false
}
