// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminScimTokens struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The attributes property
    attributes AdminScimTokens_attributesable
    // The id property
    id *string
    // The type property
    typeEscaped *AdminScimTokens_type
}
// NewAdminScimTokens instantiates a new AdminScimTokens and sets the default values.
func NewAdminScimTokens()(*AdminScimTokens) {
    m := &AdminScimTokens{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAdminScimTokensFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminScimTokensFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminScimTokens(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AdminScimTokens) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAttributes gets the attributes property value. The attributes property
// returns a AdminScimTokens_attributesable when successful
func (m *AdminScimTokens) GetAttributes()(AdminScimTokens_attributesable) {
    return m.attributes
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminScimTokens) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["attributes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAdminScimTokens_attributesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttributes(val.(AdminScimTokens_attributesable))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAdminScimTokens_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*AdminScimTokens_type))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *AdminScimTokens) GetId()(*string) {
    return m.id
}
// GetTypeEscaped gets the type property value. The type property
// returns a *AdminScimTokens_type when successful
func (m *AdminScimTokens) GetTypeEscaped()(*AdminScimTokens_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *AdminScimTokens) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("attributes", m.GetAttributes())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AdminScimTokens) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAttributes sets the attributes property value. The attributes property
func (m *AdminScimTokens) SetAttributes(value AdminScimTokens_attributesable)() {
    m.attributes = value
}
// SetId sets the id property value. The id property
func (m *AdminScimTokens) SetId(value *string)() {
    m.id = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *AdminScimTokens) SetTypeEscaped(value *AdminScimTokens_type)() {
    m.typeEscaped = value
}
type AdminScimTokensable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttributes()(AdminScimTokens_attributesable)
    GetId()(*string)
    GetTypeEscaped()(*AdminScimTokens_type)
    SetAttributes(value AdminScimTokens_attributesable)()
    SetId(value *string)()
    SetTypeEscaped(value *AdminScimTokens_type)()
}
