// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AdminOrganizations_attributes struct {
    // The accessBetaTools property
    accessBetaTools *bool
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The agentsCeilingOverride property
    agentsCeilingOverride *int32
    // The applyTimeout property
    applyTimeout *string
    // The discardedAt property
    discardedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The externalId property
    externalId *string
    // The globalModuleSharing property
    globalModuleSharing *bool
    // The globalProviderSharing property
    globalProviderSharing *bool
    // The hcpId property
    hcpId *string
    // The isDisabled property
    isDisabled *bool
    // The moduleConsumingOrganizationsCount property
    moduleConsumingOrganizationsCount *int32
    // The name property
    name *string
    // The notificationEmail property
    notificationEmail *string
    // The permissions property
    permissions AdminOrganizations_attributes_permissionsable
    // The planTimeout property
    planTimeout *string
    // The providerConsumingOrganizationsCount property
    providerConsumingOrganizationsCount *int32
    // The runsCeilingOverride property
    runsCeilingOverride *int32
    // The ssoEnabled property
    ssoEnabled *bool
    // The terraformBuildWorkerApplyTimeout property
    // Deprecated: 
    terraformBuildWorkerApplyTimeout *string
    // The terraformBuildWorkerPlanTimeout property
    // Deprecated: 
    terraformBuildWorkerPlanTimeout *string
    // The terraformWorkerSudoEnabled property
    terraformWorkerSudoEnabled *bool
    // The totalModulesCount property
    totalModulesCount *int32
    // The totalProvidersCount property
    totalProvidersCount *int32
    // The workspaceLimit property
    workspaceLimit *int32
}
// NewAdminOrganizations_attributes instantiates a new AdminOrganizations_attributes and sets the default values.
func NewAdminOrganizations_attributes()(*AdminOrganizations_attributes) {
    m := &AdminOrganizations_attributes{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAdminOrganizations_attributesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAdminOrganizations_attributesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAdminOrganizations_attributes(), nil
}
// GetAccessBetaTools gets the access-beta-tools property value. The accessBetaTools property
// returns a *bool when successful
func (m *AdminOrganizations_attributes) GetAccessBetaTools()(*bool) {
    return m.accessBetaTools
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AdminOrganizations_attributes) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAgentsCeilingOverride gets the agents-ceiling-override property value. The agentsCeilingOverride property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetAgentsCeilingOverride()(*int32) {
    return m.agentsCeilingOverride
}
// GetApplyTimeout gets the apply-timeout property value. The applyTimeout property
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetApplyTimeout()(*string) {
    return m.applyTimeout
}
// GetDiscardedAt gets the discarded-at property value. The discardedAt property
// returns a *Time when successful
func (m *AdminOrganizations_attributes) GetDiscardedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.discardedAt
}
// GetExternalId gets the external-id property value. The externalId property
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetExternalId()(*string) {
    return m.externalId
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AdminOrganizations_attributes) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["access-beta-tools"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAccessBetaTools(val)
        }
        return nil
    }
    res["agents-ceiling-override"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAgentsCeilingOverride(val)
        }
        return nil
    }
    res["apply-timeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetApplyTimeout(val)
        }
        return nil
    }
    res["discarded-at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDiscardedAt(val)
        }
        return nil
    }
    res["external-id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetExternalId(val)
        }
        return nil
    }
    res["global-module-sharing"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGlobalModuleSharing(val)
        }
        return nil
    }
    res["global-provider-sharing"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGlobalProviderSharing(val)
        }
        return nil
    }
    res["hcp-id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHcpId(val)
        }
        return nil
    }
    res["is-disabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIsDisabled(val)
        }
        return nil
    }
    res["module-consuming-organizations-count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetModuleConsumingOrganizationsCount(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["notification-email"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNotificationEmail(val)
        }
        return nil
    }
    res["permissions"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAdminOrganizations_attributes_permissionsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPermissions(val.(AdminOrganizations_attributes_permissionsable))
        }
        return nil
    }
    res["plan-timeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPlanTimeout(val)
        }
        return nil
    }
    res["provider-consuming-organizations-count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetProviderConsumingOrganizationsCount(val)
        }
        return nil
    }
    res["runs-ceiling-override"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRunsCeilingOverride(val)
        }
        return nil
    }
    res["sso-enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSsoEnabled(val)
        }
        return nil
    }
    res["terraform-build-worker-apply-timeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTerraformBuildWorkerApplyTimeout(val)
        }
        return nil
    }
    res["terraform-build-worker-plan-timeout"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTerraformBuildWorkerPlanTimeout(val)
        }
        return nil
    }
    res["terraform-worker-sudo-enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTerraformWorkerSudoEnabled(val)
        }
        return nil
    }
    res["total-modules-count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalModulesCount(val)
        }
        return nil
    }
    res["total-providers-count"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTotalProvidersCount(val)
        }
        return nil
    }
    res["workspace-limit"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetInt32Value()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWorkspaceLimit(val)
        }
        return nil
    }
    return res
}
// GetGlobalModuleSharing gets the global-module-sharing property value. The globalModuleSharing property
// returns a *bool when successful
func (m *AdminOrganizations_attributes) GetGlobalModuleSharing()(*bool) {
    return m.globalModuleSharing
}
// GetGlobalProviderSharing gets the global-provider-sharing property value. The globalProviderSharing property
// returns a *bool when successful
func (m *AdminOrganizations_attributes) GetGlobalProviderSharing()(*bool) {
    return m.globalProviderSharing
}
// GetHcpId gets the hcp-id property value. The hcpId property
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetHcpId()(*string) {
    return m.hcpId
}
// GetIsDisabled gets the is-disabled property value. The isDisabled property
// returns a *bool when successful
func (m *AdminOrganizations_attributes) GetIsDisabled()(*bool) {
    return m.isDisabled
}
// GetModuleConsumingOrganizationsCount gets the module-consuming-organizations-count property value. The moduleConsumingOrganizationsCount property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetModuleConsumingOrganizationsCount()(*int32) {
    return m.moduleConsumingOrganizationsCount
}
// GetName gets the name property value. The name property
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetName()(*string) {
    return m.name
}
// GetNotificationEmail gets the notification-email property value. The notificationEmail property
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetNotificationEmail()(*string) {
    return m.notificationEmail
}
// GetPermissions gets the permissions property value. The permissions property
// returns a AdminOrganizations_attributes_permissionsable when successful
func (m *AdminOrganizations_attributes) GetPermissions()(AdminOrganizations_attributes_permissionsable) {
    return m.permissions
}
// GetPlanTimeout gets the plan-timeout property value. The planTimeout property
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetPlanTimeout()(*string) {
    return m.planTimeout
}
// GetProviderConsumingOrganizationsCount gets the provider-consuming-organizations-count property value. The providerConsumingOrganizationsCount property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetProviderConsumingOrganizationsCount()(*int32) {
    return m.providerConsumingOrganizationsCount
}
// GetRunsCeilingOverride gets the runs-ceiling-override property value. The runsCeilingOverride property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetRunsCeilingOverride()(*int32) {
    return m.runsCeilingOverride
}
// GetSsoEnabled gets the sso-enabled property value. The ssoEnabled property
// returns a *bool when successful
func (m *AdminOrganizations_attributes) GetSsoEnabled()(*bool) {
    return m.ssoEnabled
}
// GetTerraformBuildWorkerApplyTimeout gets the terraform-build-worker-apply-timeout property value. The terraformBuildWorkerApplyTimeout property
// Deprecated: 
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetTerraformBuildWorkerApplyTimeout()(*string) {
    return m.terraformBuildWorkerApplyTimeout
}
// GetTerraformBuildWorkerPlanTimeout gets the terraform-build-worker-plan-timeout property value. The terraformBuildWorkerPlanTimeout property
// Deprecated: 
// returns a *string when successful
func (m *AdminOrganizations_attributes) GetTerraformBuildWorkerPlanTimeout()(*string) {
    return m.terraformBuildWorkerPlanTimeout
}
// GetTerraformWorkerSudoEnabled gets the terraform-worker-sudo-enabled property value. The terraformWorkerSudoEnabled property
// returns a *bool when successful
func (m *AdminOrganizations_attributes) GetTerraformWorkerSudoEnabled()(*bool) {
    return m.terraformWorkerSudoEnabled
}
// GetTotalModulesCount gets the total-modules-count property value. The totalModulesCount property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetTotalModulesCount()(*int32) {
    return m.totalModulesCount
}
// GetTotalProvidersCount gets the total-providers-count property value. The totalProvidersCount property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetTotalProvidersCount()(*int32) {
    return m.totalProvidersCount
}
// GetWorkspaceLimit gets the workspace-limit property value. The workspaceLimit property
// returns a *int32 when successful
func (m *AdminOrganizations_attributes) GetWorkspaceLimit()(*int32) {
    return m.workspaceLimit
}
// Serialize serializes information the current object
func (m *AdminOrganizations_attributes) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("access-beta-tools", m.GetAccessBetaTools())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("agents-ceiling-override", m.GetAgentsCeilingOverride())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("apply-timeout", m.GetApplyTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("global-module-sharing", m.GetGlobalModuleSharing())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("global-provider-sharing", m.GetGlobalProviderSharing())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("is-disabled", m.GetIsDisabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("plan-timeout", m.GetPlanTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("runs-ceiling-override", m.GetRunsCeilingOverride())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("terraform-build-worker-apply-timeout", m.GetTerraformBuildWorkerApplyTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("terraform-build-worker-plan-timeout", m.GetTerraformBuildWorkerPlanTimeout())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteBoolValue("terraform-worker-sudo-enabled", m.GetTerraformWorkerSudoEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteInt32Value("workspace-limit", m.GetWorkspaceLimit())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAccessBetaTools sets the access-beta-tools property value. The accessBetaTools property
func (m *AdminOrganizations_attributes) SetAccessBetaTools(value *bool)() {
    m.accessBetaTools = value
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AdminOrganizations_attributes) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAgentsCeilingOverride sets the agents-ceiling-override property value. The agentsCeilingOverride property
func (m *AdminOrganizations_attributes) SetAgentsCeilingOverride(value *int32)() {
    m.agentsCeilingOverride = value
}
// SetApplyTimeout sets the apply-timeout property value. The applyTimeout property
func (m *AdminOrganizations_attributes) SetApplyTimeout(value *string)() {
    m.applyTimeout = value
}
// SetDiscardedAt sets the discarded-at property value. The discardedAt property
func (m *AdminOrganizations_attributes) SetDiscardedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.discardedAt = value
}
// SetExternalId sets the external-id property value. The externalId property
func (m *AdminOrganizations_attributes) SetExternalId(value *string)() {
    m.externalId = value
}
// SetGlobalModuleSharing sets the global-module-sharing property value. The globalModuleSharing property
func (m *AdminOrganizations_attributes) SetGlobalModuleSharing(value *bool)() {
    m.globalModuleSharing = value
}
// SetGlobalProviderSharing sets the global-provider-sharing property value. The globalProviderSharing property
func (m *AdminOrganizations_attributes) SetGlobalProviderSharing(value *bool)() {
    m.globalProviderSharing = value
}
// SetHcpId sets the hcp-id property value. The hcpId property
func (m *AdminOrganizations_attributes) SetHcpId(value *string)() {
    m.hcpId = value
}
// SetIsDisabled sets the is-disabled property value. The isDisabled property
func (m *AdminOrganizations_attributes) SetIsDisabled(value *bool)() {
    m.isDisabled = value
}
// SetModuleConsumingOrganizationsCount sets the module-consuming-organizations-count property value. The moduleConsumingOrganizationsCount property
func (m *AdminOrganizations_attributes) SetModuleConsumingOrganizationsCount(value *int32)() {
    m.moduleConsumingOrganizationsCount = value
}
// SetName sets the name property value. The name property
func (m *AdminOrganizations_attributes) SetName(value *string)() {
    m.name = value
}
// SetNotificationEmail sets the notification-email property value. The notificationEmail property
func (m *AdminOrganizations_attributes) SetNotificationEmail(value *string)() {
    m.notificationEmail = value
}
// SetPermissions sets the permissions property value. The permissions property
func (m *AdminOrganizations_attributes) SetPermissions(value AdminOrganizations_attributes_permissionsable)() {
    m.permissions = value
}
// SetPlanTimeout sets the plan-timeout property value. The planTimeout property
func (m *AdminOrganizations_attributes) SetPlanTimeout(value *string)() {
    m.planTimeout = value
}
// SetProviderConsumingOrganizationsCount sets the provider-consuming-organizations-count property value. The providerConsumingOrganizationsCount property
func (m *AdminOrganizations_attributes) SetProviderConsumingOrganizationsCount(value *int32)() {
    m.providerConsumingOrganizationsCount = value
}
// SetRunsCeilingOverride sets the runs-ceiling-override property value. The runsCeilingOverride property
func (m *AdminOrganizations_attributes) SetRunsCeilingOverride(value *int32)() {
    m.runsCeilingOverride = value
}
// SetSsoEnabled sets the sso-enabled property value. The ssoEnabled property
func (m *AdminOrganizations_attributes) SetSsoEnabled(value *bool)() {
    m.ssoEnabled = value
}
// SetTerraformBuildWorkerApplyTimeout sets the terraform-build-worker-apply-timeout property value. The terraformBuildWorkerApplyTimeout property
// Deprecated: 
func (m *AdminOrganizations_attributes) SetTerraformBuildWorkerApplyTimeout(value *string)() {
    m.terraformBuildWorkerApplyTimeout = value
}
// SetTerraformBuildWorkerPlanTimeout sets the terraform-build-worker-plan-timeout property value. The terraformBuildWorkerPlanTimeout property
// Deprecated: 
func (m *AdminOrganizations_attributes) SetTerraformBuildWorkerPlanTimeout(value *string)() {
    m.terraformBuildWorkerPlanTimeout = value
}
// SetTerraformWorkerSudoEnabled sets the terraform-worker-sudo-enabled property value. The terraformWorkerSudoEnabled property
func (m *AdminOrganizations_attributes) SetTerraformWorkerSudoEnabled(value *bool)() {
    m.terraformWorkerSudoEnabled = value
}
// SetTotalModulesCount sets the total-modules-count property value. The totalModulesCount property
func (m *AdminOrganizations_attributes) SetTotalModulesCount(value *int32)() {
    m.totalModulesCount = value
}
// SetTotalProvidersCount sets the total-providers-count property value. The totalProvidersCount property
func (m *AdminOrganizations_attributes) SetTotalProvidersCount(value *int32)() {
    m.totalProvidersCount = value
}
// SetWorkspaceLimit sets the workspace-limit property value. The workspaceLimit property
func (m *AdminOrganizations_attributes) SetWorkspaceLimit(value *int32)() {
    m.workspaceLimit = value
}
type AdminOrganizations_attributesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAccessBetaTools()(*bool)
    GetAgentsCeilingOverride()(*int32)
    GetApplyTimeout()(*string)
    GetDiscardedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetExternalId()(*string)
    GetGlobalModuleSharing()(*bool)
    GetGlobalProviderSharing()(*bool)
    GetHcpId()(*string)
    GetIsDisabled()(*bool)
    GetModuleConsumingOrganizationsCount()(*int32)
    GetName()(*string)
    GetNotificationEmail()(*string)
    GetPermissions()(AdminOrganizations_attributes_permissionsable)
    GetPlanTimeout()(*string)
    GetProviderConsumingOrganizationsCount()(*int32)
    GetRunsCeilingOverride()(*int32)
    GetSsoEnabled()(*bool)
    GetTerraformBuildWorkerApplyTimeout()(*string)
    GetTerraformBuildWorkerPlanTimeout()(*string)
    GetTerraformWorkerSudoEnabled()(*bool)
    GetTotalModulesCount()(*int32)
    GetTotalProvidersCount()(*int32)
    GetWorkspaceLimit()(*int32)
    SetAccessBetaTools(value *bool)()
    SetAgentsCeilingOverride(value *int32)()
    SetApplyTimeout(value *string)()
    SetDiscardedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetExternalId(value *string)()
    SetGlobalModuleSharing(value *bool)()
    SetGlobalProviderSharing(value *bool)()
    SetHcpId(value *string)()
    SetIsDisabled(value *bool)()
    SetModuleConsumingOrganizationsCount(value *int32)()
    SetName(value *string)()
    SetNotificationEmail(value *string)()
    SetPermissions(value AdminOrganizations_attributes_permissionsable)()
    SetPlanTimeout(value *string)()
    SetProviderConsumingOrganizationsCount(value *int32)()
    SetRunsCeilingOverride(value *int32)()
    SetSsoEnabled(value *bool)()
    SetTerraformBuildWorkerApplyTimeout(value *string)()
    SetTerraformBuildWorkerPlanTimeout(value *string)()
    SetTerraformWorkerSudoEnabled(value *bool)()
    SetTotalModulesCount(value *int32)()
    SetTotalProvidersCount(value *int32)()
    SetWorkspaceLimit(value *int32)()
}
