// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type AdminSmtpSettings_type int

const (
    SMTPSETTINGS_ADMINSMTPSETTINGS_TYPE AdminSmtpSettings_type = iota
)

func (i AdminSmtpSettings_type) String() string {
    return []string{"smtp-settings"}[i]
}
func ParseAdminSmtpSettings_type(v string) (any, error) {
    result := SMTPSETTINGS_ADMINSMTPSETTINGS_TYPE
    switch v {
        case "smtp-settings":
            result = SMTPSETTINGS_ADMINSMTPSETTINGS_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeAdminSmtpSettings_type(values []AdminSmtpSettings_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i AdminSmtpSettings_type) isMultiValue() bool {
    return false
}
