// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type AssessmentSourceHasOne struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data AssessmentSourceIdentifierable
    // The links property
    links Relatedable
}
// NewAssessmentSourceHasOne instantiates a new AssessmentSourceHasOne and sets the default values.
func NewAssessmentSourceHasOne()(*AssessmentSourceHasOne) {
    m := &AssessmentSourceHasOne{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAssessmentSourceHasOneFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAssessmentSourceHasOneFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAssessmentSourceHasOne(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *AssessmentSourceHasOne) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a AssessmentSourceIdentifierable when successful
func (m *AssessmentSourceHasOne) GetData()(AssessmentSourceIdentifierable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *AssessmentSourceHasOne) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAssessmentSourceIdentifierFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(AssessmentSourceIdentifierable))
        }
        return nil
    }
    res["links"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateRelatedFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLinks(val.(Relatedable))
        }
        return nil
    }
    return res
}
// GetLinks gets the links property value. The links property
// returns a Relatedable when successful
func (m *AssessmentSourceHasOne) GetLinks()(Relatedable) {
    return m.links
}
// Serialize serializes information the current object
func (m *AssessmentSourceHasOne) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("links", m.GetLinks())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *AssessmentSourceHasOne) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *AssessmentSourceHasOne) SetData(value AssessmentSourceIdentifierable)() {
    m.data = value
}
// SetLinks sets the links property value. The links property
func (m *AssessmentSourceHasOne) SetLinks(value Relatedable)() {
    m.links = value
}
type AssessmentSourceHasOneable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()(AssessmentSourceIdentifierable)
    GetLinks()(Relatedable)
    SetData(value AssessmentSourceIdentifierable)()
    SetLinks(value Relatedable)()
}
