// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type HcpOrganizationsIdentifier_type int

const (
    HCPORGANIZATIONS_HCPORGANIZATIONSIDENTIFIER_TYPE HcpOrganizationsIdentifier_type = iota
)

func (i HcpOrganizationsIdentifier_type) String() string {
    return []string{"hcp-organizations"}[i]
}
func ParseHcpOrganizationsIdentifier_type(v string) (any, error) {
    result := HCPORGANIZATIONS_HCPORGANIZATIONSIDENTIFIER_TYPE
    switch v {
        case "hcp-organizations":
            result = HCPORGANIZATIONS_HCPORGANIZATIONSIDENTIFIER_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeHcpOrganizationsIdentifier_type(values []HcpOrganizationsIdentifier_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i HcpOrganizationsIdentifier_type) isMultiValue() bool {
    return false
}
