// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type HyokCustomerKeyVersions_relationships struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The hyokConfiguration property
    hyokConfiguration HyokConfigurationsIdable
}
// NewHyokCustomerKeyVersions_relationships instantiates a new HyokCustomerKeyVersions_relationships and sets the default values.
func NewHyokCustomerKeyVersions_relationships()(*HyokCustomerKeyVersions_relationships) {
    m := &HyokCustomerKeyVersions_relationships{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateHyokCustomerKeyVersions_relationshipsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateHyokCustomerKeyVersions_relationshipsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewHyokCustomerKeyVersions_relationships(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *HyokCustomerKeyVersions_relationships) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *HyokCustomerKeyVersions_relationships) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["hyok-configuration"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateHyokConfigurationsIdFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetHyokConfiguration(val.(HyokConfigurationsIdable))
        }
        return nil
    }
    return res
}
// GetHyokConfiguration gets the hyok-configuration property value. The hyokConfiguration property
// returns a HyokConfigurationsIdable when successful
func (m *HyokCustomerKeyVersions_relationships) GetHyokConfiguration()(HyokConfigurationsIdable) {
    return m.hyokConfiguration
}
// Serialize serializes information the current object
func (m *HyokCustomerKeyVersions_relationships) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("hyok-configuration", m.GetHyokConfiguration())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *HyokCustomerKeyVersions_relationships) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetHyokConfiguration sets the hyok-configuration property value. The hyokConfiguration property
func (m *HyokCustomerKeyVersions_relationships) SetHyokConfiguration(value HyokConfigurationsIdable)() {
    m.hyokConfiguration = value
}
type HyokCustomerKeyVersions_relationshipsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetHyokConfiguration()(HyokConfigurationsIdable)
    SetHyokConfiguration(value HyokConfigurationsIdable)()
}
