// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type HyokConfigurationsId_data_type int

const (
    HYOKCONFIGURATIONS_HYOKCONFIGURATIONSID_DATA_TYPE HyokConfigurationsId_data_type = iota
)

func (i HyokConfigurationsId_data_type) String() string {
    return []string{"hyok-configurations"}[i]
}
func ParseHyokConfigurationsId_data_type(v string) (any, error) {
    result := HYOKCONFIGURATIONS_HYOKCONFIGURATIONSID_DATA_TYPE
    switch v {
        case "hyok-configurations":
            result = HYOKCONFIGURATIONS_HYOKCONFIGURATIONSID_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeHyokConfigurationsId_data_type(values []HyokConfigurationsId_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i HyokConfigurationsId_data_type) isMultiValue() bool {
    return false
}
