// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type NoCodeModules_attributes struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // Whether this no-code module is enabled for deployment.
    enabled *bool
    // Optional pinned module version for no-code deployments.
    versionPin *string
}
// NewNoCodeModules_attributes instantiates a new NoCodeModules_attributes and sets the default values.
func NewNoCodeModules_attributes()(*NoCodeModules_attributes) {
    m := &NoCodeModules_attributes{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateNoCodeModules_attributesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateNoCodeModules_attributesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewNoCodeModules_attributes(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *NoCodeModules_attributes) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetEnabled gets the enabled property value. Whether this no-code module is enabled for deployment.
// returns a *bool when successful
func (m *NoCodeModules_attributes) GetEnabled()(*bool) {
    return m.enabled
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *NoCodeModules_attributes) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["enabled"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetBoolValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetEnabled(val)
        }
        return nil
    }
    res["version-pin"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVersionPin(val)
        }
        return nil
    }
    return res
}
// GetVersionPin gets the version-pin property value. Optional pinned module version for no-code deployments.
// returns a *string when successful
func (m *NoCodeModules_attributes) GetVersionPin()(*string) {
    return m.versionPin
}
// Serialize serializes information the current object
func (m *NoCodeModules_attributes) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteBoolValue("enabled", m.GetEnabled())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("version-pin", m.GetVersionPin())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *NoCodeModules_attributes) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetEnabled sets the enabled property value. Whether this no-code module is enabled for deployment.
func (m *NoCodeModules_attributes) SetEnabled(value *bool)() {
    m.enabled = value
}
// SetVersionPin sets the version-pin property value. Optional pinned module version for no-code deployments.
func (m *NoCodeModules_attributes) SetVersionPin(value *string)() {
    m.versionPin = value
}
type NoCodeModules_attributesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetEnabled()(*bool)
    GetVersionPin()(*string)
    SetEnabled(value *bool)()
    SetVersionPin(value *string)()
}
