// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OrganizationsGetResponse_Organizationsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttributes()(Organizations_attributesable)
    GetId()(*string)
    GetLinks()(Selfable)
    GetRelationships()(Organizations_relationshipsable)
    GetTypeEscaped()(*Organizations_type)
    SetAttributes(value Organizations_attributesable)()
    SetId(value *string)()
    SetLinks(value Selfable)()
    SetRelationships(value Organizations_relationshipsable)()
    SetTypeEscaped(value *Organizations_type)()
}
