// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type OrganizationMembershipsIdentifier struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The id property
    id *string
    // The type property
    typeEscaped *OrganizationMembershipsIdentifier_type
}
// NewOrganizationMembershipsIdentifier instantiates a new OrganizationMembershipsIdentifier and sets the default values.
func NewOrganizationMembershipsIdentifier()(*OrganizationMembershipsIdentifier) {
    m := &OrganizationMembershipsIdentifier{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateOrganizationMembershipsIdentifierFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateOrganizationMembershipsIdentifierFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewOrganizationMembershipsIdentifier(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *OrganizationMembershipsIdentifier) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *OrganizationMembershipsIdentifier) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseOrganizationMembershipsIdentifier_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*OrganizationMembershipsIdentifier_type))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *OrganizationMembershipsIdentifier) GetId()(*string) {
    return m.id
}
// GetTypeEscaped gets the type property value. The type property
// returns a *OrganizationMembershipsIdentifier_type when successful
func (m *OrganizationMembershipsIdentifier) GetTypeEscaped()(*OrganizationMembershipsIdentifier_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *OrganizationMembershipsIdentifier) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("id", m.GetId())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *OrganizationMembershipsIdentifier) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetId sets the id property value. The id property
func (m *OrganizationMembershipsIdentifier) SetId(value *string)() {
    m.id = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *OrganizationMembershipsIdentifier) SetTypeEscaped(value *OrganizationMembershipsIdentifier_type)() {
    m.typeEscaped = value
}
type OrganizationMembershipsIdentifierable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetId()(*string)
    GetTypeEscaped()(*OrganizationMembershipsIdentifier_type)
    SetId(value *string)()
    SetTypeEscaped(value *OrganizationMembershipsIdentifier_type)()
}
