// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Plans_relationships_hyokEncryptedDataKey_data_type int

const (
    HYOKENCRYPTEDDATAKEYS_PLANS_RELATIONSHIPS_HYOKENCRYPTEDDATAKEY_DATA_TYPE Plans_relationships_hyokEncryptedDataKey_data_type = iota
)

func (i Plans_relationships_hyokEncryptedDataKey_data_type) String() string {
    return []string{"hyok-encrypted-data-keys"}[i]
}
func ParsePlans_relationships_hyokEncryptedDataKey_data_type(v string) (any, error) {
    result := HYOKENCRYPTEDDATAKEYS_PLANS_RELATIONSHIPS_HYOKENCRYPTEDDATAKEY_DATA_TYPE
    switch v {
        case "hyok-encrypted-data-keys":
            result = HYOKENCRYPTEDDATAKEYS_PLANS_RELATIONSHIPS_HYOKENCRYPTEDDATAKEY_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePlans_relationships_hyokEncryptedDataKey_data_type(values []Plans_relationships_hyokEncryptedDataKey_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Plans_relationships_hyokEncryptedDataKey_data_type) isMultiValue() bool {
    return false
}
