// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type PolicyEvaluationsIdentifier_type int

const (
    POLICYEVALUATIONS_POLICYEVALUATIONSIDENTIFIER_TYPE PolicyEvaluationsIdentifier_type = iota
)

func (i PolicyEvaluationsIdentifier_type) String() string {
    return []string{"policy-evaluations"}[i]
}
func ParsePolicyEvaluationsIdentifier_type(v string) (any, error) {
    result := POLICYEVALUATIONS_POLICYEVALUATIONSIDENTIFIER_TYPE
    switch v {
        case "policy-evaluations":
            result = POLICYEVALUATIONS_POLICYEVALUATIONSIDENTIFIER_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePolicyEvaluationsIdentifier_type(values []PolicyEvaluationsIdentifier_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PolicyEvaluationsIdentifier_type) isMultiValue() bool {
    return false
}
