// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Registry_type int

const (
    REGISTRYCOMPONENTS_REGISTRY_TYPE Registry_type = iota
)

func (i Registry_type) String() string {
    return []string{"registry-components"}[i]
}
func ParseRegistry_type(v string) (any, error) {
    result := REGISTRYCOMPONENTS_REGISTRY_TYPE
    switch v {
        case "registry-components":
            result = REGISTRYCOMPONENTS_REGISTRY_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRegistry_type(values []Registry_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Registry_type) isMultiValue() bool {
    return false
}
