// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type RegistryComponentFilterOptions_type int

const (
    REGISTRYCOMPONENTFILTEROPTIONS_REGISTRYCOMPONENTFILTEROPTIONS_TYPE RegistryComponentFilterOptions_type = iota
)

func (i RegistryComponentFilterOptions_type) String() string {
    return []string{"registry-component-filter-options"}[i]
}
func ParseRegistryComponentFilterOptions_type(v string) (any, error) {
    result := REGISTRYCOMPONENTFILTEROPTIONS_REGISTRYCOMPONENTFILTEROPTIONS_TYPE
    switch v {
        case "registry-component-filter-options":
            result = REGISTRYCOMPONENTFILTEROPTIONS_REGISTRYCOMPONENTFILTEROPTIONS_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRegistryComponentFilterOptions_type(values []RegistryComponentFilterOptions_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RegistryComponentFilterOptions_type) isMultiValue() bool {
    return false
}
