// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type RegistryComponents_attributes struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The createdAt property
    createdAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The description property
    description *string
    // The latestVersion property
    latestVersion *string
    // Component name. Required unless vcs-repo is provided.
    name *string
    // The namespace property
    namespace *string
    // The providers property
    providers []RegistryComponents_attributes_providersable
    // The publishedAt property
    publishedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The status property
    status *string
    // The updatedAt property
    updatedAt *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time
    // The vcsRepo property
    vcsRepo RegistryComponents_attributes_vcsRepoable
}
// NewRegistryComponents_attributes instantiates a new RegistryComponents_attributes and sets the default values.
func NewRegistryComponents_attributes()(*RegistryComponents_attributes) {
    m := &RegistryComponents_attributes{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRegistryComponents_attributesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRegistryComponents_attributesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRegistryComponents_attributes(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RegistryComponents_attributes) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetCreatedAt gets the created-at property value. The createdAt property
// returns a *Time when successful
func (m *RegistryComponents_attributes) GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.createdAt
}
// GetDescription gets the description property value. The description property
// returns a *string when successful
func (m *RegistryComponents_attributes) GetDescription()(*string) {
    return m.description
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RegistryComponents_attributes) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["created-at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetCreatedAt(val)
        }
        return nil
    }
    res["description"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDescription(val)
        }
        return nil
    }
    res["latest-version"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLatestVersion(val)
        }
        return nil
    }
    res["name"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetName(val)
        }
        return nil
    }
    res["namespace"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetNamespace(val)
        }
        return nil
    }
    res["providers"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateRegistryComponents_attributes_providersFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]RegistryComponents_attributes_providersable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(RegistryComponents_attributes_providersable)
                }
            }
            m.SetProviders(res)
        }
        return nil
    }
    res["published-at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPublishedAt(val)
        }
        return nil
    }
    res["status"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetStatus(val)
        }
        return nil
    }
    res["updated-at"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetTimeValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetUpdatedAt(val)
        }
        return nil
    }
    res["vcs-repo"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateRegistryComponents_attributes_vcsRepoFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVcsRepo(val.(RegistryComponents_attributes_vcsRepoable))
        }
        return nil
    }
    return res
}
// GetLatestVersion gets the latest-version property value. The latestVersion property
// returns a *string when successful
func (m *RegistryComponents_attributes) GetLatestVersion()(*string) {
    return m.latestVersion
}
// GetName gets the name property value. Component name. Required unless vcs-repo is provided.
// returns a *string when successful
func (m *RegistryComponents_attributes) GetName()(*string) {
    return m.name
}
// GetNamespace gets the namespace property value. The namespace property
// returns a *string when successful
func (m *RegistryComponents_attributes) GetNamespace()(*string) {
    return m.namespace
}
// GetProviders gets the providers property value. The providers property
// returns a []RegistryComponents_attributes_providersable when successful
func (m *RegistryComponents_attributes) GetProviders()([]RegistryComponents_attributes_providersable) {
    return m.providers
}
// GetPublishedAt gets the published-at property value. The publishedAt property
// returns a *Time when successful
func (m *RegistryComponents_attributes) GetPublishedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.publishedAt
}
// GetStatus gets the status property value. The status property
// returns a *string when successful
func (m *RegistryComponents_attributes) GetStatus()(*string) {
    return m.status
}
// GetUpdatedAt gets the updated-at property value. The updatedAt property
// returns a *Time when successful
func (m *RegistryComponents_attributes) GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time) {
    return m.updatedAt
}
// GetVcsRepo gets the vcs-repo property value. The vcsRepo property
// returns a RegistryComponents_attributes_vcsRepoable when successful
func (m *RegistryComponents_attributes) GetVcsRepo()(RegistryComponents_attributes_vcsRepoable) {
    return m.vcsRepo
}
// Serialize serializes information the current object
func (m *RegistryComponents_attributes) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteTimeValue("created-at", m.GetCreatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("description", m.GetDescription())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("latest-version", m.GetLatestVersion())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("name", m.GetName())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("namespace", m.GetNamespace())
        if err != nil {
            return err
        }
    }
    if m.GetProviders() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetProviders()))
        for i, v := range m.GetProviders() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("providers", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("published-at", m.GetPublishedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("status", m.GetStatus())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteTimeValue("updated-at", m.GetUpdatedAt())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("vcs-repo", m.GetVcsRepo())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RegistryComponents_attributes) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetCreatedAt sets the created-at property value. The createdAt property
func (m *RegistryComponents_attributes) SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.createdAt = value
}
// SetDescription sets the description property value. The description property
func (m *RegistryComponents_attributes) SetDescription(value *string)() {
    m.description = value
}
// SetLatestVersion sets the latest-version property value. The latestVersion property
func (m *RegistryComponents_attributes) SetLatestVersion(value *string)() {
    m.latestVersion = value
}
// SetName sets the name property value. Component name. Required unless vcs-repo is provided.
func (m *RegistryComponents_attributes) SetName(value *string)() {
    m.name = value
}
// SetNamespace sets the namespace property value. The namespace property
func (m *RegistryComponents_attributes) SetNamespace(value *string)() {
    m.namespace = value
}
// SetProviders sets the providers property value. The providers property
func (m *RegistryComponents_attributes) SetProviders(value []RegistryComponents_attributes_providersable)() {
    m.providers = value
}
// SetPublishedAt sets the published-at property value. The publishedAt property
func (m *RegistryComponents_attributes) SetPublishedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.publishedAt = value
}
// SetStatus sets the status property value. The status property
func (m *RegistryComponents_attributes) SetStatus(value *string)() {
    m.status = value
}
// SetUpdatedAt sets the updated-at property value. The updatedAt property
func (m *RegistryComponents_attributes) SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)() {
    m.updatedAt = value
}
// SetVcsRepo sets the vcs-repo property value. The vcsRepo property
func (m *RegistryComponents_attributes) SetVcsRepo(value RegistryComponents_attributes_vcsRepoable)() {
    m.vcsRepo = value
}
type RegistryComponents_attributesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetCreatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetDescription()(*string)
    GetLatestVersion()(*string)
    GetName()(*string)
    GetNamespace()(*string)
    GetProviders()([]RegistryComponents_attributes_providersable)
    GetPublishedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetStatus()(*string)
    GetUpdatedAt()(*i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)
    GetVcsRepo()(RegistryComponents_attributes_vcsRepoable)
    SetCreatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetDescription(value *string)()
    SetLatestVersion(value *string)()
    SetName(value *string)()
    SetNamespace(value *string)()
    SetProviders(value []RegistryComponents_attributes_providersable)()
    SetPublishedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetStatus(value *string)()
    SetUpdatedAt(value *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time)()
    SetVcsRepo(value RegistryComponents_attributes_vcsRepoable)()
}
