// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type RegistryProvidersIdentifier_type int

const (
    REGISTRYPROVIDERS_REGISTRYPROVIDERSIDENTIFIER_TYPE RegistryProvidersIdentifier_type = iota
)

func (i RegistryProvidersIdentifier_type) String() string {
    return []string{"registry-providers"}[i]
}
func ParseRegistryProvidersIdentifier_type(v string) (any, error) {
    result := REGISTRYPROVIDERS_REGISTRYPROVIDERSIDENTIFIER_TYPE
    switch v {
        case "registry-providers":
            result = REGISTRYPROVIDERS_REGISTRYPROVIDERSIDENTIFIER_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRegistryProvidersIdentifier_type(values []RegistryProvidersIdentifier_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RegistryProvidersIdentifier_type) isMultiValue() bool {
    return false
}
