// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StateVersionOutputsEnvelope struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // State version outputs are the output values from a Terraform state file for a workspace. They include the name and value of the output, as well as a sensitive boolean if the value should be hidden by default in UIs. There is an additional attribute, "value" that can be any type, including null if the value is sensitive and part of a list response.
    data StateVersionOutputsable
}
// NewStateVersionOutputsEnvelope instantiates a new StateVersionOutputsEnvelope and sets the default values.
func NewStateVersionOutputsEnvelope()(*StateVersionOutputsEnvelope) {
    m := &StateVersionOutputsEnvelope{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateStateVersionOutputsEnvelopeFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStateVersionOutputsEnvelopeFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStateVersionOutputsEnvelope(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StateVersionOutputsEnvelope) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. State version outputs are the output values from a Terraform state file for a workspace. They include the name and value of the output, as well as a sensitive boolean if the value should be hidden by default in UIs. There is an additional attribute, "value" that can be any type, including null if the value is sensitive and part of a list response.
// returns a StateVersionOutputsable when successful
func (m *StateVersionOutputsEnvelope) GetData()(StateVersionOutputsable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StateVersionOutputsEnvelope) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateStateVersionOutputsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(StateVersionOutputsable))
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *StateVersionOutputsEnvelope) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StateVersionOutputsEnvelope) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. State version outputs are the output values from a Terraform state file for a workspace. They include the name and value of the output, as well as a sensitive boolean if the value should be hidden by default in UIs. There is an additional attribute, "value" that can be any type, including null if the value is sensitive and part of a list response.
func (m *StateVersionOutputsEnvelope) SetData(value StateVersionOutputsable)() {
    m.data = value
}
type StateVersionOutputsEnvelopeable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()(StateVersionOutputsable)
    SetData(value StateVersionOutputsable)()
}
