// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type TeamsIdentifier_type int

const (
    TEAMS_TEAMSIDENTIFIER_TYPE TeamsIdentifier_type = iota
)

func (i TeamsIdentifier_type) String() string {
    return []string{"teams"}[i]
}
func ParseTeamsIdentifier_type(v string) (any, error) {
    result := TEAMS_TEAMSIDENTIFIER_TYPE
    switch v {
        case "teams":
            result = TEAMS_TEAMSIDENTIFIER_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTeamsIdentifier_type(values []TeamsIdentifier_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TeamsIdentifier_type) isMultiValue() bool {
    return false
}
