// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type TerraformVersions_type int

const (
    TERRAFORMVERSIONS_TERRAFORMVERSIONS_TYPE TerraformVersions_type = iota
)

func (i TerraformVersions_type) String() string {
    return []string{"terraform-versions"}[i]
}
func ParseTerraformVersions_type(v string) (any, error) {
    result := TERRAFORMVERSIONS_TERRAFORMVERSIONS_TYPE
    switch v {
        case "terraform-versions":
            result = TERRAFORMVERSIONS_TERRAFORMVERSIONS_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeTerraformVersions_type(values []TerraformVersions_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i TerraformVersions_type) isMultiValue() bool {
    return false
}
