// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type UsersHasOne_data_type int

const (
    USERS_USERSHASONE_DATA_TYPE UsersHasOne_data_type = iota
)

func (i UsersHasOne_data_type) String() string {
    return []string{"users"}[i]
}
func ParseUsersHasOne_data_type(v string) (any, error) {
    result := USERS_USERSHASONE_DATA_TYPE
    switch v {
        case "users":
            result = USERS_USERSHASONE_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeUsersHasOne_data_type(values []UsersHasOne_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i UsersHasOne_data_type) isMultiValue() bool {
    return false
}
