// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Vars_relationships struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The configurable property
    configurable ConfigurableHasOneable
    // The overwriter property
    overwriter VarsHasOneable
    // The overwritten property
    overwritten VarsHasManyable
    // The varset property
    varset VarsetsHasOneable
    // The workspace property
    workspace WorkspacesHasOneable
}
// NewVars_relationships instantiates a new Vars_relationships and sets the default values.
func NewVars_relationships()(*Vars_relationships) {
    m := &Vars_relationships{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateVars_relationshipsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateVars_relationshipsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewVars_relationships(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Vars_relationships) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetConfigurable gets the configurable property value. The configurable property
// returns a ConfigurableHasOneable when successful
func (m *Vars_relationships) GetConfigurable()(ConfigurableHasOneable) {
    return m.configurable
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Vars_relationships) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["configurable"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateConfigurableHasOneFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetConfigurable(val.(ConfigurableHasOneable))
        }
        return nil
    }
    res["overwriter"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateVarsHasOneFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOverwriter(val.(VarsHasOneable))
        }
        return nil
    }
    res["overwritten"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateVarsHasManyFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOverwritten(val.(VarsHasManyable))
        }
        return nil
    }
    res["varset"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateVarsetsHasOneFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetVarset(val.(VarsetsHasOneable))
        }
        return nil
    }
    res["workspace"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateWorkspacesHasOneFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetWorkspace(val.(WorkspacesHasOneable))
        }
        return nil
    }
    return res
}
// GetOverwriter gets the overwriter property value. The overwriter property
// returns a VarsHasOneable when successful
func (m *Vars_relationships) GetOverwriter()(VarsHasOneable) {
    return m.overwriter
}
// GetOverwritten gets the overwritten property value. The overwritten property
// returns a VarsHasManyable when successful
func (m *Vars_relationships) GetOverwritten()(VarsHasManyable) {
    return m.overwritten
}
// GetVarset gets the varset property value. The varset property
// returns a VarsetsHasOneable when successful
func (m *Vars_relationships) GetVarset()(VarsetsHasOneable) {
    return m.varset
}
// GetWorkspace gets the workspace property value. The workspace property
// returns a WorkspacesHasOneable when successful
func (m *Vars_relationships) GetWorkspace()(WorkspacesHasOneable) {
    return m.workspace
}
// Serialize serializes information the current object
func (m *Vars_relationships) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("configurable", m.GetConfigurable())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("overwriter", m.GetOverwriter())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("overwritten", m.GetOverwritten())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("varset", m.GetVarset())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("workspace", m.GetWorkspace())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Vars_relationships) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetConfigurable sets the configurable property value. The configurable property
func (m *Vars_relationships) SetConfigurable(value ConfigurableHasOneable)() {
    m.configurable = value
}
// SetOverwriter sets the overwriter property value. The overwriter property
func (m *Vars_relationships) SetOverwriter(value VarsHasOneable)() {
    m.overwriter = value
}
// SetOverwritten sets the overwritten property value. The overwritten property
func (m *Vars_relationships) SetOverwritten(value VarsHasManyable)() {
    m.overwritten = value
}
// SetVarset sets the varset property value. The varset property
func (m *Vars_relationships) SetVarset(value VarsetsHasOneable)() {
    m.varset = value
}
// SetWorkspace sets the workspace property value. The workspace property
func (m *Vars_relationships) SetWorkspace(value WorkspacesHasOneable)() {
    m.workspace = value
}
type Vars_relationshipsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetConfigurable()(ConfigurableHasOneable)
    GetOverwriter()(VarsHasOneable)
    GetOverwritten()(VarsHasManyable)
    GetVarset()(VarsetsHasOneable)
    GetWorkspace()(WorkspacesHasOneable)
    SetConfigurable(value ConfigurableHasOneable)()
    SetOverwriter(value VarsHasOneable)()
    SetOverwritten(value VarsHasManyable)()
    SetVarset(value VarsetsHasOneable)()
    SetWorkspace(value WorkspacesHasOneable)()
}
