# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Test
description: Tests go-tfe within a matrix
inputs:
  matrix_index:
    description: Index of the matrix strategy runner
    required: true
  matrix_total:
    description: Total number of matrix strategy runners
    required: true
  address:
    description: Address of the HCP Terraform instance to test against
    required: true
  admin_configuration_token:
    description: HCP Terraform Admin API Configuration role token
    required: true
  admin_provision_licenses_token:
    description: HCP Terraform Admin API Provision Licenses role token
    required: true
  admin_security_maintenance_token:
    description: HCP Terraform Admin API Security Maintenance role token
    required: true
  admin_site_admin_token:
    description: HCP Terraform Admin API Site Admin role token
    required: true
  admin_subscription_token:
    description: HCP Terraform Admin API Subscription role token
    required: true
  admin_support_token:
    description: HCP Terraform Admin API Support role token
    required: true
  admin_version_maintenance_token:
    description: HCP Terraform Admin API Version Maintenance role token
    required: true
  token:
    description: HCP Terraform token
    required: true
  oauth-client-github-token:
    description: The GitHub token used for testing OAuth scenarios for VCS workspaces
    required: false
  enterprise:
    description: Test enterprise features (`address` must be running in ON_PREM mode)
    required: false

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: go.mod
        cache: true

    - name: Sync dependencies
      shell: bash
      run: |
        go mod download
        go mod tidy

    - name: Install gotestsum
      shell: bash
      run: go install gotest.tools/gotestsum@latest

    - name: Download artifact
      id: download-artifact
      uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
      with:
        workflow_conclusion: success
        name: junit-test-summary
        if_no_artifact_found: warn
        branch: main

    - name: Split integration tests
      id: test_split
      uses: hashicorp-forge/go-test-split-action@796beedbdb3d1bea14cad2d3057bab5c5cf15fe5 # v1.0.2
      with:
        index: ${{ inputs.matrix_index }}
        total: ${{ inputs.matrix_total }}
        junit-summary: ./ci-summary.xml

    - name: Run integration tests
      shell: bash
      env:
        TFE_ADDRESS: ${{ inputs.address }}
        TFE_TOKEN: ${{ inputs.token }}
        TFE_ADMIN_CONFIGURATION_TOKEN: ${{ inputs.admin_configuration_token }}
        TFE_ADMIN_PROVISION_LICENSES_TOKEN: ${{ inputs.admin_provision_licenses_token }}
        TFE_ADMIN_SECURITY_MAINTENANCE_TOKEN: ${{ inputs.admin_security_maintenance_token }}
        TFE_ADMIN_SITE_ADMIN_TOKEN: ${{ inputs.admin_site_admin_token }}
        TFE_ADMIN_SUBSCRIPTION_TOKEN: ${{ inputs.admin_subscription_token }}
        TFE_ADMIN_SUPPORT_TOKEN: ${{ inputs.admin_support_token }}
        TFE_ADMIN_VERSION_MAINTENANCE_TOKEN: ${{ inputs.admin_version_maintenance_token }}
        TFC_RUN_TASK_URL: "http://testing-mocks.tfe:22180/runtasks/pass"
        GITHUB_POLICY_SET_IDENTIFIER: "hashicorp/test-policy-set"
        GITHUB_REGISTRY_MODULE_IDENTIFIER: "hashicorp/terraform-random-module"
        OAUTH_CLIENT_GITHUB_TOKEN: "${{ inputs.oauth-client-github-token }}"
        GO111MODULE: "on"
        ENABLE_TFE: ${{ inputs.enterprise }}
      run: |
        gotestsum --junitfile summary.xml --format short-verbose -- -parallel=1 -timeout=59m -run "${{ steps.test_split.outputs.run }}"

    - name: Upload test artifacts
      uses: actions/upload-artifact@0b7f8abb1508181956e8e162db84b466c27e18ce # v3.1.2
      with:
        name: junit-test-summary-${{ matrix.index }}
        path: summary.xml
        retention-days: 1
