# Copyright IBM Corp. 2018, 2026
# SPDX-License-Identifier: MPL-2.0

name: Test
description: Tests go-tfe
runs:
  using: composite
  steps:
    - name: set up Go
      uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
      with:
        go-version-file: go.mod
        cache: true
        cache-dependency-path: go.sum

    - name: sync dependencies
      shell: bash
      run: |
        go mod download
        go mod tidy

    - name: run tests
      shell: bash
      run: |
        make test
