# Copyright (c) HashiCorp, Inc.
# SPDX-License-Identifier: MPL-2.0

name: Test
description: Tests go-tfe

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
      with:
        go-version-file: go.mod
        cache: true

    - name: Sync dependencies
      shell: bash
      run: |
        go mod download
        go mod tidy

    - name: Run go
      shell: bash
      run: go install gotest.tools/gotestsum@3f7ff0ec4aeb6f95f5d67c998b71f272aa8a8b41 # v1.12.1

    - name: Run integration tests
      shell: bash
      env:
        ENABLE_TFE: ${{ inputs.enterprise }}
      run: |
        gotestsum --junitfile summary.xml --format short-verbose -- -parallel=1 -timeout=5m -coverprofile cover.out
