// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package workspaces

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type ItemRelationshipsRemoteStateConsumersPostRequestBody struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data []ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable
}
// NewItemRelationshipsRemoteStateConsumersPostRequestBody instantiates a new ItemRelationshipsRemoteStateConsumersPostRequestBody and sets the default values.
func NewItemRelationshipsRemoteStateConsumersPostRequestBody()(*ItemRelationshipsRemoteStateConsumersPostRequestBody) {
    m := &ItemRelationshipsRemoteStateConsumersPostRequestBody{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateItemRelationshipsRemoteStateConsumersPostRequestBodyFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemRelationshipsRemoteStateConsumersPostRequestBodyFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemRelationshipsRemoteStateConsumersPostRequestBody(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ItemRelationshipsRemoteStateConsumersPostRequestBody) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a []ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable when successful
func (m *ItemRelationshipsRemoteStateConsumersPostRequestBody) GetData()([]ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ItemRelationshipsRemoteStateConsumersPostRequestBody) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetCollectionOfObjectValues(CreateItemRelationshipsRemoteStateConsumersPostRequestBody_dataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            res := make([]ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable, len(val))
            for i, v := range val {
                if v != nil {
                    res[i] = v.(ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable)
                }
            }
            m.SetData(res)
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *ItemRelationshipsRemoteStateConsumersPostRequestBody) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetData() != nil {
        cast := make([]i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, len(m.GetData()))
        for i, v := range m.GetData() {
            if v != nil {
                cast[i] = v.(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable)
            }
        }
        err := writer.WriteCollectionOfObjectValues("data", cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ItemRelationshipsRemoteStateConsumersPostRequestBody) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *ItemRelationshipsRemoteStateConsumersPostRequestBody) SetData(value []ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable)() {
    m.data = value
}
type ItemRelationshipsRemoteStateConsumersPostRequestBodyable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()([]ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable)
    SetData(value []ItemRelationshipsRemoteStateConsumersPostRequestBody_dataable)()
}
