// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package delegatedpermissionoperations
type DelegatedPermissionOperationsPostRequestBody_data_type int

const (
    DELEGATEDPERMISSIONOPERATIONS_DELEGATEDPERMISSIONOPERATIONSPOSTREQUESTBODY_DATA_TYPE DelegatedPermissionOperationsPostRequestBody_data_type = iota
)

func (i DelegatedPermissionOperationsPostRequestBody_data_type) String() string {
    return []string{"delegated-permission-operations"}[i]
}
func ParseDelegatedPermissionOperationsPostRequestBody_data_type(v string) (any, error) {
    result := DELEGATEDPERMISSIONOPERATIONS_DELEGATEDPERMISSIONOPERATIONSPOSTREQUESTBODY_DATA_TYPE
    switch v {
        case "delegated-permission-operations":
            result = DELEGATEDPERMISSIONOPERATIONS_DELEGATEDPERMISSIONOPERATIONSPOSTREQUESTBODY_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeDelegatedPermissionOperationsPostRequestBody_data_type(values []DelegatedPermissionOperationsPostRequestBody_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i DelegatedPermissionOperationsPostRequestBody_data_type) isMultiValue() bool {
    return false
}
