// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package oidcconfigurations

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
    ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f "github.com/hashicorp/go-tfe/api/models"
)

type ItemWithOidc_configuration_PatchResponse struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable
}
// ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data composed type wrapper for classes ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable, ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable, ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable, ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable
type ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data struct {
    // Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable
    awsOidcConfiguration ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable
    // Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable
    azureOidcConfiguration ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable
    // Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable
    gcpOidcConfiguration ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable
    // Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable
    vaultOidcConfiguration ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable
}
// NewItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data instantiates a new ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data and sets the default values.
func NewItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data()(*ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) {
    m := &ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data{
    }
    return m
}
// CreateItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    result := NewItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data()
    if parseNode != nil {
        mappingValueNode, err := parseNode.GetChildNode("")
        if err != nil {
            return nil, err
        }
        if mappingValueNode != nil {
            mappingValue, err := mappingValueNode.GetStringValue()
            if err != nil {
                return nil, err
            }
            if mappingValue != nil {
            }
        }
    }
    return result, nil
}
// GetAwsOidcConfiguration gets the awsOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable
// returns a AwsOidcConfigurationable when successful
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) GetAwsOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable) {
    return m.awsOidcConfiguration
}
// GetAzureOidcConfiguration gets the azureOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable
// returns a AzureOidcConfigurationable when successful
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) GetAzureOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable) {
    return m.azureOidcConfiguration
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    if m.GetAwsOidcConfiguration() != nil {
        return m.GetAwsOidcConfiguration().GetFieldDeserializers()
    } else if m.GetAzureOidcConfiguration() != nil {
        return m.GetAzureOidcConfiguration().GetFieldDeserializers()
    } else if m.GetGcpOidcConfiguration() != nil {
        return m.GetGcpOidcConfiguration().GetFieldDeserializers()
    } else if m.GetVaultOidcConfiguration() != nil {
        return m.GetVaultOidcConfiguration().GetFieldDeserializers()
    }
    return make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
}
// GetGcpOidcConfiguration gets the gcpOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable
// returns a GcpOidcConfigurationable when successful
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) GetGcpOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable) {
    return m.gcpOidcConfiguration
}
// GetIsComposedType determines if the current object is a wrapper around a composed type
// returns a bool when successful
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) GetIsComposedType()(bool) {
    return true
}
// GetVaultOidcConfiguration gets the vaultOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable
// returns a VaultOidcConfigurationable when successful
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) GetVaultOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable) {
    return m.vaultOidcConfiguration
}
// Serialize serializes information the current object
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    if m.GetAwsOidcConfiguration() != nil {
        err := writer.WriteObjectValue("", m.GetAwsOidcConfiguration())
        if err != nil {
            return err
        }
    } else if m.GetAzureOidcConfiguration() != nil {
        err := writer.WriteObjectValue("", m.GetAzureOidcConfiguration())
        if err != nil {
            return err
        }
    } else if m.GetGcpOidcConfiguration() != nil {
        err := writer.WriteObjectValue("", m.GetGcpOidcConfiguration())
        if err != nil {
            return err
        }
    } else if m.GetVaultOidcConfiguration() != nil {
        err := writer.WriteObjectValue("", m.GetVaultOidcConfiguration())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAwsOidcConfiguration sets the awsOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) SetAwsOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable)() {
    m.awsOidcConfiguration = value
}
// SetAzureOidcConfiguration sets the azureOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) SetAzureOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable)() {
    m.azureOidcConfiguration = value
}
// SetGcpOidcConfiguration sets the gcpOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) SetGcpOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable)() {
    m.gcpOidcConfiguration = value
}
// SetVaultOidcConfiguration sets the vaultOidcConfiguration property value. Composed type representation for type ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable
func (m *ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_data) SetVaultOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable)() {
    m.vaultOidcConfiguration = value
}
type ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAwsOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable)
    GetAzureOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable)
    GetGcpOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable)
    GetVaultOidcConfiguration()(ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable)
    SetAwsOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AwsOidcConfigurationable)()
    SetAzureOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.AzureOidcConfigurationable)()
    SetGcpOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.GcpOidcConfigurationable)()
    SetVaultOidcConfiguration(value ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.VaultOidcConfigurationable)()
}
// NewItemWithOidc_configuration_PatchResponse instantiates a new ItemWithOidc_configuration_PatchResponse and sets the default values.
func NewItemWithOidc_configuration_PatchResponse()(*ItemWithOidc_configuration_PatchResponse) {
    m := &ItemWithOidc_configuration_PatchResponse{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateItemWithOidc_configuration_PatchResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemWithOidc_configuration_PatchResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemWithOidc_configuration_PatchResponse(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *ItemWithOidc_configuration_PatchResponse) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable when successful
func (m *ItemWithOidc_configuration_PatchResponse) GetData()(ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *ItemWithOidc_configuration_PatchResponse) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable))
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *ItemWithOidc_configuration_PatchResponse) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *ItemWithOidc_configuration_PatchResponse) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *ItemWithOidc_configuration_PatchResponse) SetData(value ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable)() {
    m.data = value
}
type ItemWithOidc_configuration_PatchResponseable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()(ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable)
    SetData(value ItemWithOidc_configuration_PatchResponse_WithOidc_configuration_PatchResponse_dataable)()
}
