// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package agentpools

import (
    "context"
    i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e "time"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f "github.com/hashicorp/go-tfe/api/models"
)

// ItemAgentsRequestBuilder builds and executes requests for operations under \agent-pools\{agent_pool_id}\agents
type ItemAgentsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemAgentsRequestBuilderGetQueryParameters list all agents in the specified agent pool.
type ItemAgentsRequestBuilderGetQueryParameters struct {
    // Accepts a date in ISO8601 format (ex. `2020-08-11T10:41:23Z`).
    FilterlastPingSince *i336074805fc853987abe6f7fe3ad97a6a6f3077a16391fec744f671a015fbd7e.Time `uriparametername:"filter%5Blast%2Dping%2Dsince%5D"`
    // The page number to retrieve.
    Pagenumber *int32 `uriparametername:"page%5Bnumber%5D"`
    // The number of items to retrieve per page. Defaults to 20.
    Pagesize *int32 `uriparametername:"page%5Bsize%5D"`
    // Allows sorting the returned agents. Valid value is "created-at". Prepending a hyphen to the sort parameter will reverse the order (e.g. "-name").
    Sort *string `uriparametername:"sort"`
}
// NewItemAgentsRequestBuilderInternal instantiates a new ItemAgentsRequestBuilder and sets the default values.
func NewItemAgentsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAgentsRequestBuilder) {
    m := &ItemAgentsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/agent-pools/{agent_pool_id}/agents{?filter%5Blast%2Dping%2Dsince%5D*,page%5Bnumber%5D*,page%5Bsize%5D*,sort*}", pathParameters),
    }
    return m
}
// NewItemAgentsRequestBuilder instantiates a new ItemAgentsRequestBuilder and sets the default values.
func NewItemAgentsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemAgentsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemAgentsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get list all agents in the specified agent pool.
// returns a ItemAgentsGetResponseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *ItemAgentsRequestBuilder) Get(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ItemAgentsRequestBuilderGetQueryParameters])(ItemAgentsGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemAgentsGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemAgentsGetResponseable), nil
}
// ToGetRequestInformation list all agents in the specified agent pool.
// returns a *RequestInformation when successful
func (m *ItemAgentsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestConfiguration[ItemAgentsRequestBuilderGetQueryParameters])(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ConfigureRequestInformation(requestInfo, requestConfiguration)
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemAgentsRequestBuilder when successful
func (m *ItemAgentsRequestBuilder) WithUrl(rawUrl string)(*ItemAgentsRequestBuilder) {
    return NewItemAgentsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
