// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type Account struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The attributes property
    attributes Account_attributesable
    // The id property
    id *string
    // The links property
    links Selfable
    // The relationships property
    relationships Account_relationshipsable
    // The type property
    typeEscaped *Account_type
}
// NewAccount instantiates a new Account and sets the default values.
func NewAccount()(*Account) {
    m := &Account{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateAccountFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateAccountFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewAccount(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *Account) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetAttributes gets the attributes property value. The attributes property
// returns a Account_attributesable when successful
func (m *Account) GetAttributes()(Account_attributesable) {
    return m.attributes
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *Account) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["attributes"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAccount_attributesFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetAttributes(val.(Account_attributesable))
        }
        return nil
    }
    res["id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetId(val)
        }
        return nil
    }
    res["links"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateSelfFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetLinks(val.(Selfable))
        }
        return nil
    }
    res["relationships"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateAccount_relationshipsFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetRelationships(val.(Account_relationshipsable))
        }
        return nil
    }
    res["type"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetEnumValue(ParseAccount_type)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTypeEscaped(val.(*Account_type))
        }
        return nil
    }
    return res
}
// GetId gets the id property value. The id property
// returns a *string when successful
func (m *Account) GetId()(*string) {
    return m.id
}
// GetLinks gets the links property value. The links property
// returns a Selfable when successful
func (m *Account) GetLinks()(Selfable) {
    return m.links
}
// GetRelationships gets the relationships property value. The relationships property
// returns a Account_relationshipsable when successful
func (m *Account) GetRelationships()(Account_relationshipsable) {
    return m.relationships
}
// GetTypeEscaped gets the type property value. The type property
// returns a *Account_type when successful
func (m *Account) GetTypeEscaped()(*Account_type) {
    return m.typeEscaped
}
// Serialize serializes information the current object
func (m *Account) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("attributes", m.GetAttributes())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("links", m.GetLinks())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteObjectValue("relationships", m.GetRelationships())
        if err != nil {
            return err
        }
    }
    if m.GetTypeEscaped() != nil {
        cast := (*m.GetTypeEscaped()).String()
        err := writer.WriteStringValue("type", &cast)
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *Account) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetAttributes sets the attributes property value. The attributes property
func (m *Account) SetAttributes(value Account_attributesable)() {
    m.attributes = value
}
// SetId sets the id property value. The id property
func (m *Account) SetId(value *string)() {
    m.id = value
}
// SetLinks sets the links property value. The links property
func (m *Account) SetLinks(value Selfable)() {
    m.links = value
}
// SetRelationships sets the relationships property value. The relationships property
func (m *Account) SetRelationships(value Account_relationshipsable)() {
    m.relationships = value
}
// SetTypeEscaped sets the type property value. The type property
func (m *Account) SetTypeEscaped(value *Account_type)() {
    m.typeEscaped = value
}
type Accountable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetAttributes()(Account_attributesable)
    GetId()(*string)
    GetLinks()(Selfable)
    GetRelationships()(Account_relationshipsable)
    GetTypeEscaped()(*Account_type)
    SetAttributes(value Account_attributesable)()
    SetId(value *string)()
    SetLinks(value Selfable)()
    SetRelationships(value Account_relationshipsable)()
    SetTypeEscaped(value *Account_type)()
}
