// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type GithubAppRepo_type int

const (
    GITHUBAPPREPOS_GITHUBAPPREPO_TYPE GithubAppRepo_type = iota
)

func (i GithubAppRepo_type) String() string {
    return []string{"github-app-repos"}[i]
}
func ParseGithubAppRepo_type(v string) (any, error) {
    result := GITHUBAPPREPOS_GITHUBAPPREPO_TYPE
    switch v {
        case "github-app-repos":
            result = GITHUBAPPREPOS_GITHUBAPPREPO_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeGithubAppRepo_type(values []GithubAppRepo_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i GithubAppRepo_type) isMultiValue() bool {
    return false
}
