// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type PolicySetOutcome_type int

const (
    POLICYSETOUTCOMES_POLICYSETOUTCOME_TYPE PolicySetOutcome_type = iota
)

func (i PolicySetOutcome_type) String() string {
    return []string{"policy-set-outcomes"}[i]
}
func ParsePolicySetOutcome_type(v string) (any, error) {
    result := POLICYSETOUTCOMES_POLICYSETOUTCOME_TYPE
    switch v {
        case "policy-set-outcomes":
            result = POLICYSETOUTCOMES_POLICYSETOUTCOME_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePolicySetOutcome_type(values []PolicySetOutcome_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PolicySetOutcome_type) isMultiValue() bool {
    return false
}
