// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type PolicySetVersion_attributes_status int

const (
    PENDING_POLICYSETVERSION_ATTRIBUTES_STATUS PolicySetVersion_attributes_status = iota
    INGRESSING_POLICYSETVERSION_ATTRIBUTES_STATUS
    READY_POLICYSETVERSION_ATTRIBUTES_STATUS
    ERRORED_POLICYSETVERSION_ATTRIBUTES_STATUS
    CANCELED_POLICYSETVERSION_ATTRIBUTES_STATUS
)

func (i PolicySetVersion_attributes_status) String() string {
    return []string{"pending", "ingressing", "ready", "errored", "canceled"}[i]
}
func ParsePolicySetVersion_attributes_status(v string) (any, error) {
    result := PENDING_POLICYSETVERSION_ATTRIBUTES_STATUS
    switch v {
        case "pending":
            result = PENDING_POLICYSETVERSION_ATTRIBUTES_STATUS
        case "ingressing":
            result = INGRESSING_POLICYSETVERSION_ATTRIBUTES_STATUS
        case "ready":
            result = READY_POLICYSETVERSION_ATTRIBUTES_STATUS
        case "errored":
            result = ERRORED_POLICYSETVERSION_ATTRIBUTES_STATUS
        case "canceled":
            result = CANCELED_POLICYSETVERSION_ATTRIBUTES_STATUS
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializePolicySetVersion_attributes_status(values []PolicySetVersion_attributes_status) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i PolicySetVersion_attributes_status) isMultiValue() bool {
    return false
}
