// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type PolicySetVersions_relationships struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The policySet property
    policySet PolicySetsIdable
}
// NewPolicySetVersions_relationships instantiates a new PolicySetVersions_relationships and sets the default values.
func NewPolicySetVersions_relationships()(*PolicySetVersions_relationships) {
    m := &PolicySetVersions_relationships{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreatePolicySetVersions_relationshipsFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreatePolicySetVersions_relationshipsFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewPolicySetVersions_relationships(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *PolicySetVersions_relationships) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *PolicySetVersions_relationships) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["policy-set"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreatePolicySetsIdFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetPolicySet(val.(PolicySetsIdable))
        }
        return nil
    }
    return res
}
// GetPolicySet gets the policy-set property value. The policySet property
// returns a PolicySetsIdable when successful
func (m *PolicySetVersions_relationships) GetPolicySet()(PolicySetsIdable) {
    return m.policySet
}
// Serialize serializes information the current object
func (m *PolicySetVersions_relationships) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("policy-set", m.GetPolicySet())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *PolicySetVersions_relationships) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetPolicySet sets the policy-set property value. The policySet property
func (m *PolicySetVersions_relationships) SetPolicySet(value PolicySetsIdable)() {
    m.policySet = value
}
type PolicySetVersions_relationshipsable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetPolicySet()(PolicySetsIdable)
    SetPolicySet(value PolicySetsIdable)()
}
