// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// RegistryComponent_attributes_vcsRepo vCS repository configuration and mono repo publishing settings
type RegistryComponent_attributes_vcsRepo struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The displayIdentifier property
    displayIdentifier *string
    // The githubAppInstallationId property
    githubAppInstallationId *string
    // The identifier property
    identifier *string
    // The oauthTokenId property
    oauthTokenId *string
    // Source directory path within the repository for mono repo publishing
    sourceDirectory *string
    // Tag prefix for mono repo publishing to filter relevant tags
    tagPrefix *string
}
// NewRegistryComponent_attributes_vcsRepo instantiates a new RegistryComponent_attributes_vcsRepo and sets the default values.
func NewRegistryComponent_attributes_vcsRepo()(*RegistryComponent_attributes_vcsRepo) {
    m := &RegistryComponent_attributes_vcsRepo{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateRegistryComponent_attributes_vcsRepoFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateRegistryComponent_attributes_vcsRepoFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewRegistryComponent_attributes_vcsRepo(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *RegistryComponent_attributes_vcsRepo) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetDisplayIdentifier gets the display-identifier property value. The displayIdentifier property
// returns a *string when successful
func (m *RegistryComponent_attributes_vcsRepo) GetDisplayIdentifier()(*string) {
    return m.displayIdentifier
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *RegistryComponent_attributes_vcsRepo) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["display-identifier"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetDisplayIdentifier(val)
        }
        return nil
    }
    res["github-app-installation-id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetGithubAppInstallationId(val)
        }
        return nil
    }
    res["identifier"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetIdentifier(val)
        }
        return nil
    }
    res["oauth-token-id"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetOauthTokenId(val)
        }
        return nil
    }
    res["source-directory"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetSourceDirectory(val)
        }
        return nil
    }
    res["tag-prefix"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetStringValue()
        if err != nil {
            return err
        }
        if val != nil {
            m.SetTagPrefix(val)
        }
        return nil
    }
    return res
}
// GetGithubAppInstallationId gets the github-app-installation-id property value. The githubAppInstallationId property
// returns a *string when successful
func (m *RegistryComponent_attributes_vcsRepo) GetGithubAppInstallationId()(*string) {
    return m.githubAppInstallationId
}
// GetIdentifier gets the identifier property value. The identifier property
// returns a *string when successful
func (m *RegistryComponent_attributes_vcsRepo) GetIdentifier()(*string) {
    return m.identifier
}
// GetOauthTokenId gets the oauth-token-id property value. The oauthTokenId property
// returns a *string when successful
func (m *RegistryComponent_attributes_vcsRepo) GetOauthTokenId()(*string) {
    return m.oauthTokenId
}
// GetSourceDirectory gets the source-directory property value. Source directory path within the repository for mono repo publishing
// returns a *string when successful
func (m *RegistryComponent_attributes_vcsRepo) GetSourceDirectory()(*string) {
    return m.sourceDirectory
}
// GetTagPrefix gets the tag-prefix property value. Tag prefix for mono repo publishing to filter relevant tags
// returns a *string when successful
func (m *RegistryComponent_attributes_vcsRepo) GetTagPrefix()(*string) {
    return m.tagPrefix
}
// Serialize serializes information the current object
func (m *RegistryComponent_attributes_vcsRepo) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteStringValue("display-identifier", m.GetDisplayIdentifier())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("github-app-installation-id", m.GetGithubAppInstallationId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("identifier", m.GetIdentifier())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteStringValue("oauth-token-id", m.GetOauthTokenId())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *RegistryComponent_attributes_vcsRepo) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetDisplayIdentifier sets the display-identifier property value. The displayIdentifier property
func (m *RegistryComponent_attributes_vcsRepo) SetDisplayIdentifier(value *string)() {
    m.displayIdentifier = value
}
// SetGithubAppInstallationId sets the github-app-installation-id property value. The githubAppInstallationId property
func (m *RegistryComponent_attributes_vcsRepo) SetGithubAppInstallationId(value *string)() {
    m.githubAppInstallationId = value
}
// SetIdentifier sets the identifier property value. The identifier property
func (m *RegistryComponent_attributes_vcsRepo) SetIdentifier(value *string)() {
    m.identifier = value
}
// SetOauthTokenId sets the oauth-token-id property value. The oauthTokenId property
func (m *RegistryComponent_attributes_vcsRepo) SetOauthTokenId(value *string)() {
    m.oauthTokenId = value
}
// SetSourceDirectory sets the source-directory property value. Source directory path within the repository for mono repo publishing
func (m *RegistryComponent_attributes_vcsRepo) SetSourceDirectory(value *string)() {
    m.sourceDirectory = value
}
// SetTagPrefix sets the tag-prefix property value. Tag prefix for mono repo publishing to filter relevant tags
func (m *RegistryComponent_attributes_vcsRepo) SetTagPrefix(value *string)() {
    m.tagPrefix = value
}
type RegistryComponent_attributes_vcsRepoable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetDisplayIdentifier()(*string)
    GetGithubAppInstallationId()(*string)
    GetIdentifier()(*string)
    GetOauthTokenId()(*string)
    GetSourceDirectory()(*string)
    GetTagPrefix()(*string)
    SetDisplayIdentifier(value *string)()
    SetGithubAppInstallationId(value *string)()
    SetIdentifier(value *string)()
    SetOauthTokenId(value *string)()
    SetSourceDirectory(value *string)()
    SetTagPrefix(value *string)()
}
