// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type RegistryComponentCreateVcs_type int

const (
    REGISTRY_REGISTRYCOMPONENTCREATEVCS_TYPE RegistryComponentCreateVcs_type = iota
)

func (i RegistryComponentCreateVcs_type) String() string {
    return []string{"registry"}[i]
}
func ParseRegistryComponentCreateVcs_type(v string) (any, error) {
    result := REGISTRY_REGISTRYCOMPONENTCREATEVCS_TYPE
    switch v {
        case "registry":
            result = REGISTRY_REGISTRYCOMPONENTCREATEVCS_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRegistryComponentCreateVcs_type(values []RegistryComponentCreateVcs_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RegistryComponentCreateVcs_type) isMultiValue() bool {
    return false
}
