// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type RegistryComponent_type int

const (
    REGISTRY_REGISTRYCOMPONENT_TYPE RegistryComponent_type = iota
)

func (i RegistryComponent_type) String() string {
    return []string{"registry"}[i]
}
func ParseRegistryComponent_type(v string) (any, error) {
    result := REGISTRY_REGISTRYCOMPONENT_TYPE
    switch v {
        case "registry":
            result = REGISTRY_REGISTRYCOMPONENT_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeRegistryComponent_type(values []RegistryComponent_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i RegistryComponent_type) isMultiValue() bool {
    return false
}
