// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

type StackConfiguration_relationships_stackDeploymentGroupSummaries struct {
    // Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
    additionalData map[string]any
    // The data property
    data StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable
}
// NewStackConfiguration_relationships_stackDeploymentGroupSummaries instantiates a new StackConfiguration_relationships_stackDeploymentGroupSummaries and sets the default values.
func NewStackConfiguration_relationships_stackDeploymentGroupSummaries()(*StackConfiguration_relationships_stackDeploymentGroupSummaries) {
    m := &StackConfiguration_relationships_stackDeploymentGroupSummaries{
    }
    m.SetAdditionalData(make(map[string]any))
    return m
}
// CreateStackConfiguration_relationships_stackDeploymentGroupSummariesFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateStackConfiguration_relationships_stackDeploymentGroupSummariesFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewStackConfiguration_relationships_stackDeploymentGroupSummaries(), nil
}
// GetAdditionalData gets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
// returns a map[string]any when successful
func (m *StackConfiguration_relationships_stackDeploymentGroupSummaries) GetAdditionalData()(map[string]any) {
    return m.additionalData
}
// GetData gets the data property value. The data property
// returns a StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable when successful
func (m *StackConfiguration_relationships_stackDeploymentGroupSummaries) GetData()(StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable) {
    return m.data
}
// GetFieldDeserializers the deserialization information for the current model
// returns a map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error) when successful
func (m *StackConfiguration_relationships_stackDeploymentGroupSummaries) GetFieldDeserializers()(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error)) {
    res := make(map[string]func(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(error))
    res["data"] = func (n i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode) error {
        val, err := n.GetObjectValue(CreateStackConfiguration_relationships_stackDeploymentGroupSummaries_dataFromDiscriminatorValue)
        if err != nil {
            return err
        }
        if val != nil {
            m.SetData(val.(StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable))
        }
        return nil
    }
    return res
}
// Serialize serializes information the current object
func (m *StackConfiguration_relationships_stackDeploymentGroupSummaries) Serialize(writer i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.SerializationWriter)(error) {
    {
        err := writer.WriteObjectValue("data", m.GetData())
        if err != nil {
            return err
        }
    }
    {
        err := writer.WriteAdditionalData(m.GetAdditionalData())
        if err != nil {
            return err
        }
    }
    return nil
}
// SetAdditionalData sets the AdditionalData property value. Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
func (m *StackConfiguration_relationships_stackDeploymentGroupSummaries) SetAdditionalData(value map[string]any)() {
    m.additionalData = value
}
// SetData sets the data property value. The data property
func (m *StackConfiguration_relationships_stackDeploymentGroupSummaries) SetData(value StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable)() {
    m.data = value
}
type StackConfiguration_relationships_stackDeploymentGroupSummariesable interface {
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.AdditionalDataHolder
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
    GetData()(StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable)
    SetData(value StackConfiguration_relationships_stackDeploymentGroupSummaries_dataable)()
}
