// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type StackState_type int

const (
    STACKSTATES_STACKSTATE_TYPE StackState_type = iota
)

func (i StackState_type) String() string {
    return []string{"stack-states"}[i]
}
func ParseStackState_type(v string) (any, error) {
    result := STACKSTATES_STACKSTATE_TYPE
    switch v {
        case "stack-states":
            result = STACKSTATES_STACKSTATE_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeStackState_type(values []StackState_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i StackState_type) isMultiValue() bool {
    return false
}
