// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package models
type Workspace_relationships_currentStateVersion_data_type int

const (
    STATEVERSIONS_WORKSPACE_RELATIONSHIPS_CURRENTSTATEVERSION_DATA_TYPE Workspace_relationships_currentStateVersion_data_type = iota
)

func (i Workspace_relationships_currentStateVersion_data_type) String() string {
    return []string{"state-versions"}[i]
}
func ParseWorkspace_relationships_currentStateVersion_data_type(v string) (any, error) {
    result := STATEVERSIONS_WORKSPACE_RELATIONSHIPS_CURRENTSTATEVERSION_DATA_TYPE
    switch v {
        case "state-versions":
            result = STATEVERSIONS_WORKSPACE_RELATIONSHIPS_CURRENTSTATEVERSION_DATA_TYPE
        default:
            return nil, nil
    }
    return &result, nil
}
func SerializeWorkspace_relationships_currentStateVersion_data_type(values []Workspace_relationships_currentStateVersion_data_type) []string {
    result := make([]string, len(values))
    for i, v := range values {
        result[i] = v.String()
    }
    return result
}
func (i Workspace_relationships_currentStateVersion_data_type) isMultiValue() bool {
    return false
}
