// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package stacks

import (
    "context"
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f "github.com/microsoft/kiota-abstractions-go"
    ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f "github.com/hashicorp/go-tfe/api/models"
    i9211ae54a69c06e280d6692a3438030059f00d21a14ac46221d369a152c0428f "github.com/hashicorp/go-tfe/api/stacks/item/stackdeployments"
)

// ItemStackDeploymentsRequestBuilder builds and executes requests for operations under \stacks\{stack_id}\stack-deployments
type ItemStackDeploymentsRequestBuilder struct {
    i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.BaseRequestBuilder
}
// ItemStackDeploymentsRequestBuilderGetQueryParameters list deployments for a stack.
type ItemStackDeploymentsRequestBuilderGetQueryParameters struct {
    // If omitted, the endpoint will return the first page.
    Pagenumber *int32 `uriparametername:"page%5Bnumber%5D"`
    // If omitted, the endpoint will return 20 per page.
    Pagesize *int32 `uriparametername:"page%5Bsize%5D"`
    // A search query string. Stack deployments are searchable by deployment name.
    Q *string `uriparametername:"q"`
    // Allows sorting by deployment name, 'deployment' or '-deployment' for descending.
    // Deprecated: This property is deprecated, use SortAsGetSortQueryParameterType instead
    Sort *string `uriparametername:"sort"`
    // Allows sorting by deployment name, 'deployment' or '-deployment' for descending.
    SortAsGetSortQueryParameterType *i9211ae54a69c06e280d6692a3438030059f00d21a14ac46221d369a152c0428f.GetSortQueryParameterType `uriparametername:"sort"`
}
// ItemStackDeploymentsRequestBuilderGetRequestConfiguration configuration for the request such as headers, query parameters, and middleware options.
type ItemStackDeploymentsRequestBuilderGetRequestConfiguration struct {
    // Request headers
    Headers *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestHeaders
    // Request options
    Options []i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestOption
    // Request query parameters
    QueryParameters *ItemStackDeploymentsRequestBuilderGetQueryParameters
}
// ByDeploymentId gets an item from the github.com/hashicorp/go-tfe/api.stacks.item.stackDeployments.item collection
// returns a *ItemStackDeploymentsDeploymentItemRequestBuilder when successful
func (m *ItemStackDeploymentsRequestBuilder) ByDeploymentId(deploymentId string)(*ItemStackDeploymentsDeploymentItemRequestBuilder) {
    urlTplParams := make(map[string]string)
    for idx, item := range m.BaseRequestBuilder.PathParameters {
        urlTplParams[idx] = item
    }
    if deploymentId != "" {
        urlTplParams["deployment%2Did"] = deploymentId
    }
    return NewItemStackDeploymentsDeploymentItemRequestBuilderInternal(urlTplParams, m.BaseRequestBuilder.RequestAdapter)
}
// NewItemStackDeploymentsRequestBuilderInternal instantiates a new ItemStackDeploymentsRequestBuilder and sets the default values.
func NewItemStackDeploymentsRequestBuilderInternal(pathParameters map[string]string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemStackDeploymentsRequestBuilder) {
    m := &ItemStackDeploymentsRequestBuilder{
        BaseRequestBuilder: *i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewBaseRequestBuilder(requestAdapter, "{+baseurl}/stacks/{stack_id}/stack-deployments{?page%5Bnumber%5D*,page%5Bsize%5D*,q*,sort*}", pathParameters),
    }
    return m
}
// NewItemStackDeploymentsRequestBuilder instantiates a new ItemStackDeploymentsRequestBuilder and sets the default values.
func NewItemStackDeploymentsRequestBuilder(rawUrl string, requestAdapter i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestAdapter)(*ItemStackDeploymentsRequestBuilder) {
    urlParams := make(map[string]string)
    urlParams["request-raw-url"] = rawUrl
    return NewItemStackDeploymentsRequestBuilderInternal(urlParams, requestAdapter)
}
// Get list deployments for a stack.
// Deprecated: This method is obsolete. Use GetAsStackDeploymentsGetResponse instead.
// returns a ItemStackDeploymentsResponseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *ItemStackDeploymentsRequestBuilder) Get(ctx context.Context, requestConfiguration *ItemStackDeploymentsRequestBuilderGetRequestConfiguration)(ItemStackDeploymentsResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemStackDeploymentsResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemStackDeploymentsResponseable), nil
}
// GetAsStackDeploymentsGetResponse list deployments for a stack.
// returns a ItemStackDeploymentsGetResponseable when successful
// returns a Errors error when the service returns a 4XX or 5XX status code
func (m *ItemStackDeploymentsRequestBuilder) GetAsStackDeploymentsGetResponse(ctx context.Context, requestConfiguration *ItemStackDeploymentsRequestBuilderGetRequestConfiguration)(ItemStackDeploymentsGetResponseable, error) {
    requestInfo, err := m.ToGetRequestInformation(ctx, requestConfiguration);
    if err != nil {
        return nil, err
    }
    errorMapping := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.ErrorMappings {
        "XXX": ie0c034c41cc7c7bacea8ad562c1d20027757bf421f1a5ace132a302c2bb1878f.CreateErrorsFromDiscriminatorValue,
    }
    res, err := m.BaseRequestBuilder.RequestAdapter.Send(ctx, requestInfo, CreateItemStackDeploymentsGetResponseFromDiscriminatorValue, errorMapping)
    if err != nil {
        return nil, err
    }
    if res == nil {
        return nil, nil
    }
    return res.(ItemStackDeploymentsGetResponseable), nil
}
// ToGetRequestInformation list deployments for a stack.
// returns a *RequestInformation when successful
func (m *ItemStackDeploymentsRequestBuilder) ToGetRequestInformation(ctx context.Context, requestConfiguration *ItemStackDeploymentsRequestBuilderGetRequestConfiguration)(*i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.RequestInformation, error) {
    requestInfo := i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.NewRequestInformationWithMethodAndUrlTemplateAndPathParameters(i2ae4187f7daee263371cb1c977df639813ab50ffa529013b7437480d1ec0158f.GET, m.BaseRequestBuilder.UrlTemplate, m.BaseRequestBuilder.PathParameters)
    if requestConfiguration != nil {
        if requestConfiguration.QueryParameters != nil {
            requestInfo.AddQueryParameters(*(requestConfiguration.QueryParameters))
        }
        requestInfo.Headers.AddAll(requestConfiguration.Headers)
        requestInfo.AddRequestOptions(requestConfiguration.Options)
    }
    requestInfo.Headers.TryAdd("Accept", "application/vnd.api+json")
    return requestInfo, nil
}
// WithUrl returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
// returns a *ItemStackDeploymentsRequestBuilder when successful
func (m *ItemStackDeploymentsRequestBuilder) WithUrl(rawUrl string)(*ItemStackDeploymentsRequestBuilder) {
    return NewItemStackDeploymentsRequestBuilder(rawUrl, m.BaseRequestBuilder.RequestAdapter);
}
