// Code generated by Microsoft Kiota - DO NOT EDIT.
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

package cidrrangelists

import (
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91 "github.com/microsoft/kiota-abstractions-go/serialization"
)

// Deprecated: This class is obsolete. Use ItemRelationshipsCidrRangesGetResponseable instead.
type ItemRelationshipsCidrRangesResponse struct {
    ItemRelationshipsCidrRangesGetResponse
}
// NewItemRelationshipsCidrRangesResponse instantiates a new ItemRelationshipsCidrRangesResponse and sets the default values.
func NewItemRelationshipsCidrRangesResponse()(*ItemRelationshipsCidrRangesResponse) {
    m := &ItemRelationshipsCidrRangesResponse{
        ItemRelationshipsCidrRangesGetResponse: *NewItemRelationshipsCidrRangesGetResponse(),
    }
    return m
}
// CreateItemRelationshipsCidrRangesResponseFromDiscriminatorValue creates a new instance of the appropriate class based on discriminator value
// returns a Parsable when successful
func CreateItemRelationshipsCidrRangesResponseFromDiscriminatorValue(parseNode i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.ParseNode)(i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable, error) {
    return NewItemRelationshipsCidrRangesResponse(), nil
}
// Deprecated: This class is obsolete. Use ItemRelationshipsCidrRangesGetResponseable instead.
type ItemRelationshipsCidrRangesResponseable interface {
    ItemRelationshipsCidrRangesGetResponseable
    i878a80d2330e89d26896388a3f487eef27b0a0e6c010c493bf80be1452208f91.Parsable
}
